### ISSUE TITLE
imagecreatefromstring(): Data is not in a recognized format

### ISSUE THREAD

**Issue by pjeutr** [SimpleSoftwareIO/simple-qrcode#105]
I get this error seems the same like https://github.com/SimpleSoftwareIO/simple-qrcode/issues/77
But I tried several things and it's not working.
 I dumbed it down to the below example, using your png from github
This is the code I use in my blade, when I remove the merge line, it's working:

```
<img src="data:image/png;base64, {!! 
            base64_encode(
                QrCode::format('png')->size(400)
                    ->merge('https://github.com/SimpleSoftwareIO/simple-qrcode/raw/develop/tests/Images/simplesoftware-icon-grey-blue.png', 0.3, true)
                    ->errorCorrection('H')->generate('lol')
                ) 
            !!} ">
```

**Comment by pjeutr** [comment]
It works now for me with another png. The png needs to be in a certain format?

**Comment by SimplyCorey** [comment]
We will be redesigning qrcode to be better shortly.  Is there any details that you could provide that caused this to fail?

**Comment by Zoha** [comment]
Hi.
I have same issue . I tried different images with different types but still not working . 
Do you have any suggestion ?
