### ISSUE TITLE
XML tag outputed?

### ISSUE THREAD

**Issue by huglester** [SimpleSoftwareIO/simple-qrcode#11]
Hello,

when I echo the SVG qrcode, I also see this:
&lt;?xml version="1.0" encoding="UTF-8"?&gt;

right before the qrcode is printed.

What could that be?

Thanks!

**Comment by SimplyCorey** [comment]
Can you show me a screen shot?  The SVG uses XML to output and should not be showing up.

**Comment by SimplyCorey** [comment]
Closing this due to not hearing anything back.

**Comment by BlueManLine** [comment]
That happening also to me.

I'm using mpdf to generate PDF document with the qrcode. Unfortunatelly as @huglester said the <?xml tag is shown in the PDF document :/

![image](https://cloud.githubusercontent.com/assets/3807650/17476231/37e19520-5d5f-11e6-95ca-2cc2a3412725.png)

I'm using Laravel 5.1 with the composer.json entries:
```json
"simplesoftwareio/simple-qrcode": "^1.3",
"mpdf/mpdf": "^6.1",
```

The example code is:
```html
<p class="text-center">
    {!! QrCode::size(200)->generate(Request::url()) !!}
</p>
```

When I return the laravel view directly to a browser then the xml tag isnt display. It display just on generated pdf document.

**Comment by SimplyThomas** [comment]
@BlueManLine  just checking -- are you also using SVG? Have you tried this with another format like PNG?

This might be an issue with how mpdf renders SVGs and would be outside the scope of our support.

**Comment by bluemanos** [comment]
@SimplyThomas thank you for quick reply :+1: 
Unfortunately on other places I do not use SVG, I just want to use it with the QrCode.
Finally I used the PNG format fetched by a local url, not the inline PNG image you are suggesting..

If I will have time (does any developer have time? :D) I will check the issue with other PDF generator library.

**Comment by BlueManLine** [comment]
@SimplyThomas thank you for quick reply :+1: 
Unfortunately on other places I do not use SVG, I just want to use it with the QrCode.
Finally I used the PNG format fetched by a local url, not the inline PNG image you are suggesting..

If I will have time (does any developer have time? :D) I will check the issue with other PDF generator library.

**Comment by SimplyCorey** [comment]
@BlueManLine Does using the PNG URL resolve your issue?

Out of curiosity, what are you building?  It looks interesting.

**Comment by BlueManLine** [comment]
@SimplyCorey yes, the png url resolve my issue. I can attach an extra _GET parameters to easily manipulate the size and margins, so generally I have the same possibilities as with inline qrcode (or even higher - when someday I'm going to change the qrcode library then the changes will affect just one place :))

About my project - I'm building a receipt (or actually docket) which is printing on a remote thermal printer :)

**Comment by kopgzdevth** [comment]
can you replace it and this code work!!
    $qrcode=QrCode::encoding('UTF-8')->size(50)->generate('A basic example of QR code!');
    $qrcode=str_replace('<?xml version="1.0" encoding="UTF-8"?>',"",$qrcode); //replace to empty

**Comment by heshanmax** [comment]
I have the same issue i'm using 
 "niklasravnsborg/laravel-pdf"

it prints the qrcode but XML tag printed as @BlueManLine.

Any help

**Comment by rajeevunni** [comment]
I too encountered similar issue while generating pdf with mpdf library. i just checked @[kopgzdevth](https://github.com/kopgzdevth) answer and replaced the entire xml tag from my code. 

$qrcode=QrCode::encoding('UTF-8')->size(50)->generate('A basic example of QR code!');
$qrcode=str_replace('<?xml version="1.0" encoding="UTF-8"?>',"",$qrcode); 
![image](https://user-images.githubusercontent.com/7204593/166867412-d854e9bc-39f7-423c-872b-a7b1149a3b9f.png)
Edit: inline xml code is somehow replaced by editor. so I am attaching an image

**Comment by Nahiyan47** [comment]
I solved this problem.
Qr code returns an object. At first you have to convert this to string. then slice until that portion where that xml code ends.

           $qrcode=QrCode::size(50)->generate('A basic example of QR code!');
           $code = (string)$qrcode;
           echo substr($code,38);

this perfectly shows my qrcode without xml code
