### ISSUE TITLE
Position image inside QrCode

### ISSUE THREAD

**Issue by atefrihane** [SimpleSoftwareIO/simple-qrcode#112]
Hey Guys
I have this code below I would like to change data position to the bottom-right of the Qrcode
it's currently centred
how can I do that?

       `        $newTable=Table::create([
            'qr_code' => $qrCodeName,
            'num_table' => $i+1,
            'status' => 1,
            'restaurant_id' =>$restaurant->id,
        ]);
        $numTableImage = Image::canvas(100, 350)->fill('rgba(0, 0, 0, 0.5)');
        $numTableImage->text($newTable->num_table, 100, 200, function($font) {
            $font->file(public_path('templates/backOffice/restaurant/fonts/OpenSans-Bold.ttf'));
            $font->size(100);
            $font->color('#fdf6e3');
            $font->align('center');
        });

        $numTableImage->save('storage/uploads/restaurants/table'.$newTable->num_table.'.png');
        $qrCode = str_random(10) . "-" . $newTable->id;
        $data = $numTableImage->encode();
        QrCode::format('png')->mergeString($data)->size(450)->generate($qrCode, $qrCodeName);
`

**Comment by trantuanngoctn97** [comment]
I have same issue. Anybody can help us ?

**Comment by SimplyCorey** [comment]
I am confused on the request.  You want to move the image location within the QrCode?
