### ISSUE TITLE
file_get_contents failed to open stream

### ISSUE THREAD

**Issue by exskuller** [SimpleSoftwareIO/simple-qrcode#114]
i have error : 
`file_get_contents(http://localhost:8000/assets/img/logo_2_0_white.png): failed to open stream: HTTP request failed! (View: /Applications/XAMPP/xamppfiles/htdocs/bo/resources/views/merchant/index.blade.php)`
my code:
`<data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge(url('assets/img/logo_2_0_white.png'), 0.3, true)->size(500)->errorCorrection('H')->generate('Welcome to kerneldev.com!')) !!} ">`

can u help me, please

**Comment by SimplyThomas** [comment]
This looks like an issue with the `url()` helper and not SimpleQrCode. Try using `asset()` helper instead, but this is not an issue with our package.
