### ISSUE TITLE
PNG outputs weird characters 

### ISSUE THREAD

**Issue by Zianwar** [SimpleSoftwareIO/simple-qrcode#12]
I have this : 
```
Route::get('/test', function(){
    return QrCode::encoding('UTF-8')->format('png')->size(500)->generate('Make me a QrCode!');
});
```
and when I visit the route ``` /test ```, I get a weird characters, something like : 

```
�PNG


IHDR��D�H�	pHYs���+	.IDATx����N�Eч���dtgO,A�N�ص��jUgVo3:o�������o?�'�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A�$�A���������?�7������O��y��s�ƭ�;@���;@���;@
```

Shouldn't I get a PNG image ? or how do get a ```<img ...>``` tag ?

**Comment by kplese** [comment]
Well, you should have something like this in order to download the image:
header('Content-Description: File Transfer');
		header("Content-type: application/octet-stream");
		header("Content-disposition: attachment; filename=printed_marketing.png");
		exit(QrCode::size(100)->margin(1)->format('png')->generate("My QR code content"));

**Comment by Zianwar** [comment]
Thank you !
