### ISSUE TITLE
Class qrcode does not exist

### ISSUE THREAD

**Issue by jlubeck** [SimpleSoftwareIO/simple-qrcode#120]
Hi! I'm using the library on Laravel 5.5

It's working great on my dev machine, but when I put everything on production, i get the error: 
`Class 'QrCode' not found`

What is weird, is that if I include `use SimpleSoftwareIO\QrCode\Facades\QrCode;` at the top of the file, I then get the slighly different error:
`Class qrcode does not exist`

I already checked the other similar issues, but they are all having laraval 5.4 or lower, which uses a different installation approach.

Thank you for your help!

**Comment by koseimori** [comment]
Did you install it with composer?
Have you already tried this command?

`composer dump-autoload`

**Comment by jlubeck** [comment]
Thank you so much. I don't know which one fixed it. But doing both dump and install fixed the issue. Thanks!
