### ISSUE TITLE
Website is down for instructions

### ISSUE THREAD

**Issue by Wolrab1** [SimpleSoftwareIO/simple-qrcode#122]
Your website is down for documentation

**Comment by vstyler96** [comment]
Yes, I cannot read the documentation u_u

**Comment by chaicai333** [comment]
Is any alternate website for documentation ?

**Comment by chaicai333** [comment]
https://github.com/SimpleSoftwareIO/simple-qrcode/tree/develop/docs/en

**Comment by SimplyCorey** [comment]
Thanks, we have gone ahead and fixed the issue.
