### ISSUE TITLE
documentation webside down

### ISSUE THREAD

**Issue by keevitaja** [SimpleSoftwareIO/simple-qrcode#125]
https://www.simplesoftware.io/simple-qrcode

```
curl -I https://www.simplesoftware.io/simple-qrcode 
curl: (7) Failed to connect to www.simplesoftware.io port 443: Connection refused
```

**Comment by mhetreramesh** [comment]
Would be great if the basic documentation to installation is on the project readme file.

**Comment by trantuanngoctn97** [comment]
I found this link documentation from repository [https://github.com/SimpleSoftwareIO/simple-qrcode/tree/develop/docs/en](https://github.com/SimpleSoftwareIO/simple-qrcode/tree/develop/docs/en)

**Comment by SimplyCorey** [comment]
Sorry guys, we fixed the issue.
