### ISSUE TITLE
QRCode geo - no mark?

### ISSUE THREAD

**Issue by huglester** [SimpleSoftwareIO/simple-qrcode#13]
Hello

I am able to generate PNG GEO qrcode. But when maps are opened, there are no marker on the map.. it is just centered at that location.. is it normal behaviuor? Or maybe I can add marker somehow? 

Thanks!

**Comment by SimplyCorey** [comment]
This really depends on what app you are using to open the QrCode.  Most apps just center the location.

**Comment by SimplyCorey** [comment]
You could read the Google Maps API and generate a link that would open a map that would have a pointer on it.  I think this is the only way to get the results on all apps.

https://developers.google.com/maps/
