### ISSUE TITLE
QrCode merge image position problem

### ISSUE THREAD

**Issue by dduenas-tumipos** [SimpleSoftwareIO/simple-qrcode#130]
Hello!, im trying to make something like the first image, but i only get the second image. Anyone here have the same problem? Thanks for your comments

*FIRST IMAGE*
![Screen Shot 2019-07-03 at 5 02 57 PM](https://user-images.githubusercontent.com/33697143/60627748-ba7dee00-9db4-11e9-98e3-41fa2a09a7d4.png)

*SECOND IMAGE*
![Screen Shot 2019-07-03 at 4 58 36 PM](https://user-images.githubusercontent.com/33697143/60627781-ccf82780-9db4-11e9-8e29-8ec9b5061285.png)

**Comment by SimplyCorey** [comment]
You want to remove the transparency on the image.

**Comment by SimplyCorey** [comment]
Closing as stale.
