### ISSUE TITLE
Class qrcode does not exist

### ISSUE THREAD

**Issue by Kadinar-Novel** [SimpleSoftwareIO/simple-qrcode#131]
Hi i try to generate qrcode from my controller, I already include use SimpleSoftwareIO\QrCode\Facades\QrCode; but still get error Class qrcode does not exist.. After installed i'm also did composer dumpautoload..
Please help..

**Comment by SimplyCorey** [comment]
Did you register it in your app.php file?  Provide an example controller please.

**Comment by Kadinar-Novel** [comment]
yes i did,, but it's done i put use SimpleSoftwareIO\QrCode\BaconQrCodeGenerator; in my controller n it work..
thx this libs it so awesome..

**Comment by SimplyCorey** [comment]
your welcome
