### ISSUE TITLE
size not working at all

### ISSUE THREAD

**Issue by yasirmehmood1** [SimpleSoftwareIO/simple-qrcode#132]
Hi 
im working with simple-qrcode but in my case size() is not working its generating 33x33 size image although i have provided different dimensions but still not working saving the image in 33x33

**Comment by SimplyCorey** [comment]
Please provide example code

**Comment by yasirmehmood1** [comment]
QrCode::size(500)
            ->format('png')
            ->generate('ItSolutionStuff.com', public_path('images/qrcode1.png'));

i just simply put that code it generated the image properly but size was not changing i have tried different sizes but no working

**Comment by nebtden** [comment]
yes,I'm not work,too

**Comment by edianogama** [comment]
Yes, the parameter size doesn't work for me.

**Comment by edianogama** [comment]
I understand.
The Format needs to be the first method called or it will overwrite all of the other set properties.

Try this:

`QrCode::format('png')->size(500)`

**Comment by SimplyCorey** [comment]
How are you inserting this into your page?  Are you saving the image and putting it in an image tag?  Are you base64 encoding it?

**Comment by edianogama** [comment]
> How are you inserting this into your page? Are you saving the image and putting it in an image tag? Are you base64 encoding it?

In page and when I send a email.

**Blade Email:** 
`<img src="{!!$message->embedData(QrCode::format('png')->size(300)->generate( $order['order_number']), $order['order_number'].'.png', 'image/png')!!}">`

**Blade view:**
` {!! QrCode::size(250)->generate($item->order_number); !!}`

**Comment by SimplyCorey** [comment]
This is resolved in v3 which I am finishing up the docs for and will push up this week.
