### ISSUE TITLE
Email QRCode shows "+" instead of spaces in subject & Body

### ISSUE THREAD

**Issue by rizdem** [SimpleSoftwareIO/simple-qrcode#135]
Any ideas how to show the body & subject string with spaces instead of + icon?

**Comment by SimplyCorey** [comment]
Please provide a code sample of where this is happening.  I am unsure of what your issue is.

**Comment by GenedyMohamed** [comment]
Shows plus instead of spaces in iOS

$attrs = $user_qrcode->attributes()->get();
$qrcode_content = $qrcode->email($attrs[0]->value, $attrs[1]->value, $attrs[2]->value);
