### ISSUE TITLE
[Unreported] Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor

### ISSUE THREAD

**Issue by quangvision** [SimpleSoftwareIO/simple-qrcode#139]
Hello
 I am using Laradock to run Nginx, PHP 7.3, MariaDB, php-worker and Redis. 
 I setup `QUEUE_DRIVER=redis` and laravel-worker.conf as below:
`
[program:myproject-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/myproject/artisan queue:work redis --tries=1
autostart=true
autorestart=true
numprocs=2
user=root
redirect_stderr=true
stdout_logfile=/var/www/myproject/worker.log
`
When I run `docker-compose up php-worker`, the job was failed with error `Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor()`.
The weird thing is if I stop php-worker but manually run `php artisan queue:work redis --tries=1` then job processed successfully.
Do you think it is a bug or something?
Thanks :)

**Comment by TEDinTW** [comment]
I got the same issue too...
Still try to find something out.

**Comment by SimplyCorey** [comment]
Can you provide your code please?

**Comment by SimplyCorey** [comment]
Closing as stale.
