### ISSUE TITLE
Embed logo be scaled to SQUARE size

### ISSUE THREAD

**Issue by quangvision** [SimpleSoftwareIO/simple-qrcode#142]
On my project, using this package to generate QRcodes with embed logo that not in square form but in horizontal form. Logo embed is scaled to square and this makes my logo looks ugly.
       For example, this is my logo: 
![ta](https://user-images.githubusercontent.com/12606323/67255766-ea5d1880-f4ad-11e9-806c-ab481dc75a80.png)
       Qrcode generated as this:
![TA](https://user-images.githubusercontent.com/12606323/67255836-4aec5580-f4ae-11e9-82b1-7086949d9827.png)
       What I want is to have logo embed as it is without being scaled to square like this:
![frame (4)](https://user-images.githubusercontent.com/12606323/67255981-fd241d00-f4ae-11e9-9ba3-663cbc63b2fc.png)
       Do you have any idea how to achieve this?
     Thanks :)

**Comment by SimplyCorey** [comment]
I've added this to 3.0

**Comment by thisisandreww** [comment]
I had a workaround on this..

`    private function calculateOverlap($percentage)
    {
        $ratio = $this->mergeImageWidth / $this->mergeImageHeight;
        $this->postMergeImageWidth = $this->sourceImageWidth * $percentage;
        $this->postMergeImageHeight = $this->postMergeImageWidth / $ratio;
    }`

**Comment by SimplyCorey** [comment]
Thanks @thisisandreww.  I'll use this code to update the file in the next release.

**Comment by SimplyCorey** [comment]
Fixed in 4.1.0

**Comment by codetestmg** [comment]
@SimplyCorey   is there any example for the above scenario? Any document how to do using code

Thanks
