### ISSUE TITLE
the qrcode with logo cannot work

### ISSUE THREAD

**Issue by michelleyaoyao** [SimpleSoftwareIO/simple-qrcode#143]
QrCode::format('png')->merge('/resources/logo/test.png',0.3)->size(1000)->generate('this ');

When the second parameter of merge is 0.1 .the qrcode work well 。

 but when I set it to 0.3 , the qrcode not work. 

please help me . thankyou .

**Comment by SimplyCorey** [comment]
You need to increase your error correction to account for the image.
