### ISSUE TITLE
Size not working

### ISSUE THREAD

**Issue by mabehiry** [SimpleSoftwareIO/simple-qrcode#144]
This is the code I use:
\QrCode::size(300)->format('png')->generate($request->code, $qrPath);
But it generates a very small image: 29px.
How can I increase the size to 300px?

**Comment by Astriel** [comment]
Same for me.

**Comment by anthonyaxenov** [comment]
@mabehiry @Astriel 
Read the [documentation](https://www.simplesoftware.io/simple-qrcode/#docs-usage) carefully:
> **Format Change**
> Watch out! The format method must be called before any other formatting options such as size, color, backgroundColor, and margin.

To change size of QR you need to specify its format first, like this:
```php
\QrCode::format('png')->size(300)->generate($request->code, $qrPath);
```
