### ISSUE TITLE
Laravel 5.7 | Unable to print Qr code in my Email

### ISSUE THREAD

**Issue by marcq64** [SimpleSoftwareIO/simple-qrcode#145]
Hi,

I have tried several methods to try to print my qr code into my blade file :

Here my blade file :
`

@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/customer/customer.css') }}" >
@stop

@component('mail::layout')
{{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => 'http://commandes.patisseriemage.ch/admin/login'])
            <img src="{{ asset('assets/img/logo.png') }}" alt="{{ config('app.name') }} Logo">
        @endcomponent
    @endslot
    
@php

    $hostname = $_SERVER['HTTP_HOST'];
    $producturl = '/admin/slug?filter_column[orders_detail_new.orderID][type]=in&filter_column[orders_detail_new.orderID][value]=';
    $prodprefix = 'prod';
    $rowID = '{{ $products->orderID }}';
    $qrurl = $hostname.$producturl;
    $qrcode = $qrurl.$rowID;
    # dd($qrurl);

@endphp

{{-- Body --}}
<body bgcolor="#F6E9DC" style="width:100%">

    <div style="width: 100%">
        <div style="width: 100%">
            <h2>Votre commande</h2>

            {{--dd($content)--}}
            
            <p>Bonjour {{ $content['user']->Civilité }} {{ $content['user']->Prénom }} {{ $content['user']->Nom }},</p>
            <p>Vous venez d'effectuer une commande auprès de la Pâtisserie Mage et nous vous en remercions. Nous réaliserons votre commande dans le délai souhaité du {{ \Carbon\Carbon::parse($content['date']->Date)->format('d/m/Y') }}. Vous pourrez venir récupérer votre commande à partir de :  {{ $content['time']->Time }} heures.</p>
            <p>Vos coordonnées téléphoniques : {{ $content['user']->Mobile }}</p>
            <p>Ci-après le récapitulatif de votre commande :</p>

            <p>

                <table style="width:100%">
                    <tbody style="width: 100%">

                        @foreach($content['order'] as $products)

                            <tr> 

                                <td>

                                    @if(isset($products->rowID)) {{ '# '.$products->rowID.' | ' }} @endif
                                    @if(isset($products->Type)) {{ $products->Type.' | ' }} @endif
                                    @if(isset($products->Name)) {{ $products->Name.' | ' }} @endif
                                    @if(isset($products->Servings)) {{ $products->Servings.' | ' }} @endif
                                    @if(isset($products->Message)) {{ $products->Message.' | ' }} @endif                                  
                                    @if(isset($products->DecoChoco) && $products->Type === 'Gâteaux' || $products->Type === 'Tarte' || $products->Type === 'Tarte-fine') {{ $products->DecoChoco.' | ' }} @endif
                                    @if(isset($products->DecoFlowers) && $products->Type === 'Gâteaux' || $products->Type === 'Tarte' || $products->Type === 'Tarte-fine') {{ $products->DecoFlowers.' | ' }} @endif
                                    @if(isset($products->Décoration) && $products->Type === 'Tarte' || $products->Type === 'Tarte-fine') {{ $products->Décoration.' | ' }} @endif

                                    @if(isset($products->Portions) && $products->Type === 'Pain-surprise') {{ $products->Portions.' | ' }} @endif
                                    @if(isset($products->Weight) && $products->Type === 'Pain-surprise') {{ $products->Weight.' | ' }} @endif
                                    @if(isset($products->Assortment1) && $products->Type === 'Pain-surprise') {{ $products->Assortment1.' | ' }} @endif
                                    @if(isset($products->Assortment2) && $products->Type === 'Pain-surprise') {{ $products->Assortment2.' | ' }} @endif
                                    @if(isset($products->Assortment3) && $products->Type === 'Pain-surprise') {{ $products->Assortment3.' | ' }} @endif
                                    @if(isset($products->Assortment4) && $products->Type === 'Pain-surprise') {{ $products->Assortment4.' | ' }} @endif
                                    @if(isset($products->RibbonColor) && $products->Type === 'Pain-surprise') {{ $products->RibbonColor.' | ' }} @endif

                                    @if(isset($products->SlicesCut) && $products->Type === 'Pain') {{ $products->SlicesCut.' | ' }} @endif
                                    @if(isset($products->BreadQuantity) && $products->Type === 'Pain') {{ $products->BreadQuantity.' pièce(s) | ' }} @endif
                                    
                                    @if(isset($products->AssortmentCanapes) && $products->Type === 'Salé') {{ $products->AssortmentCanapes.' | ' }} @endif
                                    @if(isset($products->AssortmentMiniPuffs) && $products->Type === 'Salé') {{ $products->AssortmentMiniPuffs.' | ' }} @endif
                                    @if(isset($products->AssortmentVolsauvent) && $products->Type === 'Salé') {{ $products->AssortmentVolsauvent.' | ' }} @endif
                                    @if(isset($products->AssortmentAppetisers) && $products->Type === 'Salé') {{ $products->AssortmentAppetisers.' | ' }} @endif
                                    @if(isset($products->SavouryQuantity) && $products->Type === 'Salé') {{ $products->SavouryQuantity.' pièce(s) | ' }} @endif
                                    @if(isset($products->SweetAssortment) && $products->Type === 'Sucré') {{ $products->SweetAssortment.' | ' }} @endif
                                    @if(isset($products->SweetQuantity) && $products->Type === 'Sucré') {{ $products->SweetQuantity.' pièce(s) | ' }} @endif
                                   
                                    Prix : CHF @if(isset($products->Total)) {{ number_format($products->Total, 2) }} @endif

                                </td>

                            </tr>

                        @endforeach
                        
                            <tr>
                                <td>
                                    Total Commande : CHF {{ number_format($content['order']->sum('Total'), 2) }}
                                </td>
                            </tr>

                    </tbody>
                </table>

            </p>
                CONTENT
            <p>

                                    <img src="{!!$message->embedData($qrcode, 'QrCode.png', 'image/png')!!}">

            </p>

        </div>

    </div>

{{--dd("stoped")--}}

</body>

{{-- Footer --}}
    @slot('footer')
        @component('mail::footer')
            <footer>
            </footer>
        @endcomponent
    @endslot

@endcomponent
`

I'm building my qr-code as follows :
`
    $hostname = $_SERVER['HTTP_HOST'];
    $producturl = '/admin/slug?filter_column[orders_detail_new.orderID][type]=in&filter_column[orders_detail_new.orderID][value]=';
    $prodprefix = 'prod';
    $rowID = '{{ $products->orderID }}';
    $qrurl = $hostname.$producturl;
    $qrcode = $qrurl.$rowID;
    # dd($qrurl);
`

When I check if all information is rendered with

`
{{ dd("stoped") }}
`

I can see that the qr code is printed.

But when I send the email, email never arrived. 

If I take the line

`
<img src="{!!$message->embedData($qrcode, 'QrCode.png', 'image/png')!!}">
`

out, then the email is sent with no issue.

Would need some expertise here since I'm stuck.

Thanks.

**Comment by putupadang** [comment]
i think that is not working because running from local serve ?

**Comment by SimplyCorey** [comment]
This is likely an issue with the email driver.  Which one are you using?

**Comment by SimplyCorey** [comment]
Closing, feel free to open a new issue if you are still having this issue.
