### ISSUE TITLE
Does not Work with Laravel Markdown Mailables

### ISSUE THREAD

**Issue by maggz69** [SimpleSoftwareIO/simple-qrcode#149]
Using `<img src="{!!$message->embedData(QrCode::format('png')->generate('Embed me into an e-mail!'), 'QrCode.png', 'image/png')!!}">` does not work with mardown mailables because the $message variable is only parsed after rendering the blade template. As such one will get an error Call to a member function embedData() on null. Meanwhile just generating the SVG image files do not display in the email.

This is with laravel V6 and using markdown mailables where you just pass the view to

**Comment by SimplyCorey** [comment]
Would an embed inline work in this case?

I would suggest not using a .png but instead base64 encoding it.

```
<img src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->generate('Embed me into an e-mail!') }}">
```

Does this solve your issue?

**Comment by maggz69** [comment]
Tested it right now. In blade (rendering email preview in browser) this works, but when sending the email it can't be seen from the client.

![Email](https://user-images.githubusercontent.com/20341115/75720361-09cb4400-5cdf-11ea-89e8-89387a67d27a.png)
![Email Preview](https://user-images.githubusercontent.com/20341115/75720449-31221100-5cdf-11ea-87d9-6ae297774697.png)

**Comment by maggz69** [comment]
As I discovered, gmail and most other webclients don't support base64 images. https://stackoverflow.com/questions/12655764/base64-not-being-decoded-in-gmail

Possible alternatives are : generating the PDF and attaching the file then editing the PDF or, not using mailables(?)

**Comment by SimplyCorey** [comment]
hmm, that is interesting.  I did not know that gmail dropped support for base64 inline images.  Thanks for letting me know.

You should be able to generate the qrcodes on demand and save them to a s3 bucket and then use the public url to put them within the email.

My other suggestion would be to include a link they can click on that generates them on the fly.  This might be better overall as you can swap out the qrcode at any time.

**Comment by SimplyCorey** [comment]
Another item you could do is generate the file locally, and then attach it to the email.
