### ISSUE TITLE
bacon/bacon-qr-code 2 Support

### ISSUE THREAD

**Issue by BirgitZ** [SimpleSoftwareIO/simple-qrcode#150]
Please add bacon/bacon-qr-code 2.0 Support for the package

**Comment by SimplyCorey** [comment]
The plan is to get simple-qrcode 3.x done this month which will include bumping all dependencies to the latest.  🙃

**Comment by SimplyCorey** [comment]
Started work on v3 this morning and wrapping this up with #100
