### ISSUE TITLE
Scale property instead of size

### ISSUE THREAD

**Issue by ArthurShlain** [SimpleSoftwareIO/simple-qrcode#152]
Need scale attribute instead of using size. I have very small pixels sometimes when QR code data is large and size specified 150..200 pixels. I need just 200-300% scaling of pixel-perfect QR code.

**Comment by ArthurShlain** [comment]
Solved by two-step QR-code generation:

```php
$scale = 2;

$qr = QrCode::format('png')->encoding('UTF-8')
  ->margin(0)->errorCorrection('M')->generate('QR code text');

$size = getimagesizefromstring($qr);
$width = $size[0];

$qr = QrCode::format('png')->encoding('UTF-8')
  ->size($width * $scale)
  ->margin(0)->errorCorrection('M')->generate($this->qrCodeText);
```

**Comment by SimplyCorey** [comment]
This is a known issue that will be solved when v3 ships.  I am going to put some time aside soon to knock this out.

**Comment by SimplyCorey** [comment]
This is resolved in v3 which will be shipped this week.
