### ISSUE TITLE
QrCode::encoding('SHIFT-JIS')

### ISSUE THREAD

**Issue by mosvict** [SimpleSoftwareIO/simple-qrcode#157]
Hello. How are you?
when you are going to release 3.0?
UTF-8 is working now but I need to use shift-jis encoding.

**Comment by SimplyCorey** [comment]
I have been busy this weekend knocking out some private code.  3.0 should launch Tuesday after a final review of the docs and a wrap up of the unit tests.  You could pull dev-develop branch for now in composer if you need this functionality now.  The api is largely stable assuming I dont fihd any bugs by Tuesday.
