### ISSUE TITLE
Call to undefined function BaconQrCode\Encoder\iconv()

### ISSUE THREAD

**Issue by rvu95** [SimpleSoftwareIO/simple-qrcode#16]
I'm using this command on my view
`{{QrCode::generate('Make me into a QrCode!')}}`
and then when I'm going to this page I'm getting this error:
`FatalErrorException in Encoder.php line 627: Call to undefined function BaconQrCode\Encoder\iconv()`

Any idea why?

**Comment by SimplyCorey** [comment]
Do you have the iconv library installed?  Are you running on Linux, Windows, or Mac?

**Comment by rvu95** [comment]
I'm running Arch Linux

Linux rvu 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

**Comment by SimplyCorey** [comment]
Please try installing PHP with incov.

http://php.net/manual/en/iconv.installation.php

**Comment by rvu95** [comment]
Done. But I'm getting this instead.

https://gist.github.com/rvu95/93f89605f322eee89b42#file-gistfile1-txt

**Comment by SimplyCorey** [comment]
This is due to Laravel escaping the output.  Use {!! {{QrCode::generate('Make me into a QrCode!') !!}

This only affects SVG format.

**Comment by rvu95** [comment]
Sorry, my bad, i forgot the correct format. It's solved, thanks :)

**Comment by SimplyCorey** [comment]
You're welcome!
