### ISSUE TITLE
upgrade 2.0 to 3.0 

### ISSUE THREAD

**Issue by mosvict** [SimpleSoftwareIO/simple-qrcode#160]
Hello. How are you?
Thank you for your update.
I updated simple-qrcode 2.0 to 3.0.
But I see this error.
Class 'SimpleSoftwareIO\QRCode\QRCodeServiceProvider' not found
I defined this code in 2.0.
SimpleSoftwareIO\QRCode\QRCodeServiceProvider::class
'QRCode' => SimpleSoftwareIO\QRCode\Facedes\QRCode::class

How to solve this problem?
And Can I use previous code to generate qr code?

**Comment by SimplyCorey** [comment]
You no longer have to define the Service provider and facede.  Laravel will pick it up automatically and it should work out of the gate.  Those files were renamed and moved around.  I'll update the docs to reflect the changes in the upgrade guide.

**Comment by mosvict** [comment]
Thanks. 
https://www.simplesoftware.io/simple-qrcode
I can't see it.

**Comment by SimplyCorey** [comment]
The website was moved to github pages and is still propagation.

You can use this: https://github.com/SimpleSoftwareIO/simple-qrcode/tree/develop/docs/en

**Comment by mosvict** [comment]
Thank you.

**Comment by SimplyCorey** [comment]
No problem, thanks for letting me know 🙃

**Comment by gwidgery** [comment]
Hi
I was having the issue described here https://github.com/SimpleSoftwareIO/simple-qrcode/issues/85 to do with margin being added to the QR codes. The thread said it was fixed in v3. I've just followed the upgrade guide but now am getting the error:

Error Class 'SimpleSoftwareIO\QrCode\QrCodeServiceProvider' not found

I've followed the steps above and removed the two entries in app.php and run composer update, but I'm still getting the error.

**Comment by mosvict** [comment]
Hi. 
I removed 2.0 and installed 3.0.
And I removed 2 lines in app.php and didn't change any code. It was working well.

**Comment by gwidgery** [comment]
I've tried that as well. But no whenever I run any php artisan command I just get that same error:

php artisan package:discover --ansi
In ProviderRepository.php line 208:
  Class 'SimpleSoftwareIO\QrCode\QrCodeServiceProvider' not found

After uninstalling it's no longer in my composer.josn, yet something in laravel is trying to find the class!

**Comment by mosvict** [comment]
Did you remove 2 lines in providers and aliases?

**Comment by gwidgery** [comment]
Yes. They're gone.

When I try and reinstall v3 now I get this error:

`composer require simplesoftwareio/simple-qrcode "~3"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:

  Class 'SimpleSoftwareIO\QrCode\QrCodeServiceProvider' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

C:\xampp\htdocs\laravel\medlink>`

**Comment by mosvict** [comment]
I did the following:
- Remove 2 lines in app.php
- composer remove simplesoftwareio/simple-qrcode
Please check composer.json after run it.
- composer require simplesoftwareio/simple-qrcode
Please check composer.json after run it.
- Please install imagick package.
You can search imagick on google.
Copy php_imagick.dll to c:\xampp\php\ext
Copy CORE*.DLL and IM*.DLL to c:\xampp\apache\bin
Restart apache and mysql service
- php artisan serve

**Comment by gwidgery** [comment]
I think I found the issue. The app.php (with those two extra lines) had been cached. I couldn't clear the cache because my php artisan commands were failing.

I manually removed them from the cached file and got past the class not found error. I've installed v3 now.

Next issue is that I'm getting another error on the page where I'm actually using the package. With v2 at the top of the controller we had

//At the top
use SimpleSoftwareIO\QrCode\Facades\QrCode;

//In my code
$qr = QrCode::generate('test.com');

But it can't find anywhere in the documentation that talks about replacing/chaning that. It throws the error:
Class 'SimpleSoftwareIO\QrCode\Facades\QrCode' not found

**Comment by mosvict** [comment]
Did you define "use SimpleSoftwareIO\QrCode\Facades\QrCode;" in controller?

I used this code.
use QrCode;

**Comment by SimplyCorey** [comment]
You should be able to call QrCode directly if it was registered with Laravel.  

You should not have to pull in the file from a use statement.

**Comment by SimplyCorey** [comment]
@gwidgery can you provide a complete code example and I will look into it.

**Comment by gwidgery** [comment]
Thanks to the both of you. It's working now by just calling QrCode. I had the long 'use' string from v2 still being used.

However the former issue with regards to the caching might crop up for other users. I think the solution would be remove those two lines from app.php, then clear the cache, then uninstall v2. If you uninstall first it leaves those two lines in the cached file. It's then looking for a model it can't find, and so php artisan commands all fail - including the one to clear the cache! The way round that was to manually edit the cached file itself.

**Comment by SimplyCorey** [comment]
@gwidgery, I agree.  I am going to get something added to the upgrade docs so this isn't an issue moving forward.  Thanks for the feedback.

**Comment by gwidgery** [comment]
@SimplyCorey Happy to help! That would be great moving forwards. Spent a few hours scratching my head on this one! I might suggest adding to the upgrade docs to change the use statement as well:
from:
`use SimpleSoftwareIO\QrCode\Facades\QrCode;`
to:
`use QrCode;`

**Comment by meshmmanuel** [comment]
Hi guys,
I'm having an issue upgrading from 2.0 to 3.0 too.

**Error**
_PHP Fatal error:  Interface 'Illuminate\Contracts\Support\DeferrableProvider' not found in C:\Users\meshm\Documents\Mealimeter\codebase\local\mealimeter-api\vendor\simplesoftwareio\simple-qrcode\src\ServiceProvider.php on line 8
In ServiceProvider.php line 8:

  Interface 'Illuminate\Contracts\Support\DeferrableProvider' not found_

**My composer.json**
`    "simplesoftwareio/simple-qrcode": "^3.0",
    "spatie/fractalistic": "^2.7",
    "spatie/laravel-fractal": "^5.4",
    "tymon/jwt-auth": "^1.0@dev"
  },
  "provide": {
    "ext-imagick": "*"
  },`

Note: Service Provide and Facade has not been added to config/app.php

**Comment by SimplyCorey** [comment]
This should be fixed in the release that will go out today (3.0.1) I removed the deferrable provider all together.
