### ISSUE TITLE
QrCode::encoding('SHIFT-JIS') is not working. 

### ISSUE THREAD

**Issue by mosvict** [SimpleSoftwareIO/simple-qrcode#161]
Hello. How are you?
I have a problem.. I already this problem in 2.0.
But I have this problem in 3.0 too.
Can you check it?

**Comment by SimplyCorey** [comment]
What's the code?

**Comment by mosvict** [comment]
QrCode::encoding('SHIFT-JIS')

**Comment by SimplyCorey** [comment]
What's the data being encoded?  I am able to run this without any issue.

**Comment by mosvict** [comment]
I will show you my code.
- in controller
$param = "会社名 " . " 郵便番号 111ー222\n";
$param .= "住所 〒106-0044東京都港区東麻布1-8-1 東麻布ISビル\n";
$pdf = PDF::loadView('index', compact(param));
$pdf->download('example.pdf');
- in view
<img src="data:image/png;base64, {{ base64_encode(QrCode::encoding('SHIFT-JIS')->format('png')->size(400)->errorCorrection('H')->generate($param)) }}">

Of course, When I use UTF-8, then it is working.
But I need to use SHIFT-JIS. When I use this, then I see error.
Please help me.

**Comment by mosvict** [comment]
Hi. Can you check it?

**Comment by SimplyCorey** [comment]
I'm confused on the issue here,  I don't experience any errors when I run this.  Are you seeing an error?  Does the QrCode not scan?
