### ISSUE TITLE
Generated QR code looks weird

### ISSUE THREAD

**Issue by ErikB26** [SimpleSoftwareIO/simple-qrcode#164]
I know, 'looks weird' is a broad term, so I'll just demonstrate it with my example:

`$image = \QrCode::size(500)->generate('hello world');`

Svg looks like this:
<img width="501" alt="qr" src="https://user-images.githubusercontent.com/23705771/85956391-e4e19780-b985-11ea-8578-d19bc33e55d3.png">

The size of the svg is correct (500x500). It just looks like scaled up or something like that?

**Comment by SimplyCorey** [comment]
How was this printed out?  Can I see how it was inserted into the HTML please.

**Comment by ErikB26** [comment]
This is what the svg looks like. 
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="500" height="500" viewBox="0 0 500 500">
  <rect x="0" y="0" width="500" height="500" fill="#ffffff"/>
  <g transform="scale(23,81)">
    <g transform="translate(0,0)">
      <path fill-rule="evenodd" d="M9 0L9 2L8 2L8 3L9 3L9 4L10 4L10 5L11 5L11 4L12 4L12 7L11 7L11 6L10 6L10 7L9 7L9 6L8 6L8 8L4 8L4 9L3 9L3 8L0 8L0 9L3 9L3 10L0 10L0 11L1 11L1 12L0 12L0 13L3 13L3 12L2 12L2 11L3 11L3 10L4 10L4 13L5 13L5 11L7 11L7 12L6 12L6 13L8 13L8 17L9 17L9 18L8 18L8 21L10 21L10 20L11 20L11 21L13 21L13 20L12 20L12 19L13 19L13 18L12 18L12 16L13 16L13 15L12 15L12 13L13 13L13 14L14 14L14 12L12 12L12 13L11 13L11 11L10 11L10 10L11 10L11 9L12 9L12 8L13 8L13 9L14 9L14 10L12 10L12 11L14 11L14 10L15 10L15 11L16 11L16 12L15 12L15 13L16 13L16 14L15 14L15 16L16 16L16 17L14 17L14 19L15 19L15 18L16 18L16 20L15 20L15 21L16 21L16 20L17 20L17 16L16 16L16 15L17 15L17 11L19 11L19 12L20 12L20 11L21 11L21 9L19 9L19 8L18 8L18 9L19 9L19 10L17 10L17 9L15 9L15 8L13 8L13 4L12 4L12 3L13 3L13 2L12 2L12 1L13 1L13 0L11 0L11 1L10 1L10 0ZM10 2L10 4L11 4L11 2ZM10 7L10 8L11 8L11 7ZM4 9L4 10L5 10L5 9ZM6 9L6 10L7 10L7 9ZM8 10L8 13L9 13L9 15L11 15L11 13L10 13L10 12L9 12L9 10ZM18 13L18 15L20 15L20 16L21 16L21 13ZM9 16L9 17L10 17L10 16ZM18 17L18 19L19 19L19 21L21 21L21 20L20 20L20 19L21 19L21 18L20 18L20 17ZM10 18L10 19L9 19L9 20L10 20L10 19L12 19L12 18ZM19 18L19 19L20 19L20 18ZM0 0L0 7L7 7L7 0ZM1 1L1 6L6 6L6 1ZM2 2L2 5L5 5L5 2ZM14 0L14 7L21 7L21 0ZM15 1L15 6L20 6L20 1ZM16 2L16 5L19 5L19 2ZM0 14L0 21L7 21L7 14ZM1 15L1 20L6 20L6 15ZM2 16L2 19L5 19L5 16Z" fill="#000000"/>
    </g>
  </g>
</svg>
```
When inserted as base64 in the src of an HTML img-tag, it also looks like that. There is no CSS involved.

**Comment by SimplyCorey** [comment]
You should not have to base64 encode a SVG file, that should only apply to a PNG.  How did you print this in the blade / HTML file?

**Comment by ErikB26** [comment]
I know I don't have to encode it, it was just one of the things I tried.

I load it into the HTML via the usual way: relative path in the src-attribute. 

But the issue is within the svg, because when i save the file and open it in a webbrowser (Chrome, Safari) it still looks the same.

**Comment by SimplyCorey** [comment]
Unfortunately, I can not reproduce this so I am going to close the issue.  3.0.1 has an upgraded dependency that might solve this issue for you.
