### ISSUE TITLE
QrCode::wiFi does not accept variables

### ISSUE THREAD

**Issue by ourada84** [SimpleSoftwareIO/simple-qrcode#168]
hi i need to generate wifi qr code from variable from database. i use laravel.

I'm trying:

` {!! QrCode :: wiFi ([$ col]); !!} `

where `$col` has value` 'ssid' => 'mywifi', 'password' => 'mypass', 'encryption' => 'WPA'`

but unfortunately the code always has the values null, null, null

any idea please? Thank you

**Comment by SimplyCorey** [comment]
I'll take a look over the upcoming days.  Thanks for reporting.

**Comment by SimplyCorey** [comment]
I am able to generate wifi qrcodes on the latest version.  I think something is wrong with your code.

Here is an example:

`QrCode::wiFi(['ssid' => 'wifi', 'password' => 'pass', 'encryption' =>  'WPA']);`
