### ISSUE TITLE
SMS separator is incorrect

### ISSUE THREAD

**Issue by sportdude** [SimpleSoftwareIO/simple-qrcode#169]
I'm unable to push my change, but the SMS qr code isn’t filling in the message box on my iPhone with the $message. The separator is incorrect. 

Line 19 of src/DataTypes/SMS.php
\-    protected $separator = ':';
\+    protected $separator = '&body=';

This works 👍

**Comment by SimplyCorey** [comment]
Thank you, I will address this in an upcoming release.
