### ISSUE TITLE
A error appear when using style('round', 0.9) in sever environment 

### ISSUE THREAD

**Issue by ZBrettonYe** [SimpleSoftwareIO/simple-qrcode#171]
In the front end, I have
 `<img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->margin(2)->eyeColor(1, 0, 204, 153, 0, 153, 119)->style('round', 0.9)->size(250)->errorCorrection('H')->merge(url($pay_type_icon), .3, true)->generate($payment->url))!!}">`

The laravel give me a message 
`too many bezier coordinates `M8 0.4500000000000000111L8 2.5499999999999998224 A0.4500000000000000111 0.4500000000000000111 0 0 0 8.4499999999999992895 3 L10.550000000000000711 3 ....`

This error doesn't appear when i tested the code on my local machine.  
On the server, without `style('round', 0.9)` the qr-code will generated.

update:
It also have something to do with the `$payment->url`, while url become too long, this many also case the problem;
My question become how to prevent this happen with style apply.

$payment->url has around 200-250 characters

**Comment by ilkerkocatepe** [comment]
I have a same error in my project. Because of url size, as yours.
I'm looking forward for answers...
Thank you...

**Comment by SimplyCorey** [comment]
Can you provide the urls that can be used for testing?  I can't seem to reproduce this.

**Comment by SimplyCorey** [comment]
Example with test stuff: ![image](https://user-images.githubusercontent.com/624784/94993023-05f4ee00-055c-11eb-8e80-89472583144a.png)

**Comment by ZBrettonYe** [comment]
it only happen when the php has low memory setting, long url and complex qrcode settings.

The error only appeared when I deployed the code on my server, it did not show up when I developed the web on my local machine with the same qrcode setting and url.

**Comment by SimplyCorey** [comment]
Interesting.  I don't think there is much I can do if PHP is running out of memory as we are using the PHP image multiplication libraries.   Thanks for reporting though.  If you have any ideas of how to solve this I am open to reopening this though.

**Comment by isasenoaji** [comment]
i suggest to make your qr lower errorCorrection. I ve a same problem with you that im using errorCorrection('Q') or ('H') and working properly with ('M'). coz i think if you set more higher errorCorrection, it will makes your qr become more complex and more computation and its mean you need more memory in your php. 

if you dont want to make it lower, you can set your php memory limit in php.ini to infinity or more value than default value (about 64 or 128M).

thank you

**Comment by MattiaMarchiorato** [comment]
Hello,

i have the same issue only on production server (with php memory_limit se to 2048), in staging or develop all works fine!

Anyone resolved this problem?
@ZBrettonYe any news?

Best

MM

**Comment by JonahSayyed** [comment]
I am also having same problem

error

[2023-09-21 05:57:36] local.ERROR: QR Code Generation Failed: too many bezier coordinates `M11 0.2999999999999999889L11 0.69999999999999995559
A0.2999999999999999889 0.2999999999999999889 0 0 1 10.699999999999999289 1
L9.3000000000000007105 1
A0.2999999999999999889 0.2999999999999999889 0 0 0 9 1.3000000000000000444
L9 1.6999999999999999556
A0.2999999999999999889 0.2999999999999999889 0 0 1 8.6999999999999992895 2
L8.3000000000000007105 2
A0.2999999999999999889 0.2999999999999999889 0 0 0 8 2.2999999999999998224
L8 7.7000000000000001776
A0.2999999999999999889 0.2999999999999999889 0 0 0 8.3000000000000007105 8
L8.6999999999999992895 8
A0.2999999999999999889 0.2999999999999999889 0 0 1 9 8.3000000000000007105
L9 8.6999999999999992895
A0.2999999999999999889 0.2999999999999999889 0 0 1 8.6999999999999992895 9
L8.3000000000000007105 9
A0.2999999999999999889 0.2999999999999999889 0 0 0 8 9.3000000000000007105
L8 9.6999999999999992895
A0.2999999999999999889 0.2999999999999999889 0 0 0 8.3000000000000007105 10
L8.6999999999999992895 10
A0.2999999999999999889 0.2999999999999999889 0 0 1 9 10.300000000000000711
L9 10.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 0 9.3000000000000007105 11
L9.6999999999999992895 11
A0.2999999999999999889 0.2999999999999999889 0 0 0 10 10.699999999999999289
L10 9.3000000000000007105
A0.2999999999999999889 0.2999999999999999889 0 0 1 10.300000000000000711 9
L10.699999999999999289 9
A0.2999999999999999889 0.2999999999999999889 0 0 1 11 9.3000000000000007105
L11 10.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 0 11.300000000000000711 11
L12.699999999999999289 11
A0.2999999999999999889 0.2999999999999999889 0 0 0 13 10.699999999999999289
L13 10.300000000000000711
A0.2999999999999999889 0.2999999999999999889 0 0 1 13.300000000000000711 10
L13.699999999999999289 10
A0.2999999999999999889 0.2999999999999999889 0 0 0 14 9.6999999999999992895
L14 9.3000000000000007105
A0.2999999999999999889 0.2999999999999999889 0 0 0 13.699999999999999289 9
L13.300000000000000711 9
A0.2999999999999999889 0.2999999999999999889 0 0 1 13 8.6999999999999992895
L13 8.3000000000000007105
A0.2999999999999999889 0.2999999999999999889 0 0 1 13.300000000000000711 8
L14.699999999999999289 8
A0.2999999999999999889 0.2999999999999999889 0 0 1 15 8.3000000000000007105
L15 10.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 1 14.699999999999999289 11
L14.300000000000000711 11
A0.2999999999999999889 0.2999999999999999889 0 0 0 14 11.300000000000000711
L14 12.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 1 13.699999999999999289 13
L13.300000000000000711 13
A0.2999999999999999889 0.2999999999999999889 0 0 0 13 13.300000000000000711
L13 13.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 1 12.699999999999999289 14
L11.300000000000000711 14
A0.2999999999999999889 0.2999999999999999889 0 0 0 11 14.300000000000000711
L11 14.699999999999999289
A0.2999999999999999889 0.2999999999999999889 0 0 1 10.699999999999999289 15
L10.300000000000000711 15
A0.2999999999999999889 0.2999999999999999889 0 0 1 10 14.699999999999999289
L10 14.300000000000000711
A0.2999999999999999889 0.2999999999999999889 0 0 0 9.6999999999999992895 14
L9.3000000000000007105 14
A0.2999999999999999889 0.2999999999999999889 0 0 1 9 13.699999999999999289
L9 12.300000000000000711
A0.2999999999999999889 0.2999999999999999889 0 0 0 8.6999999999999992895 12
L8.3000000000000007105 12
A0.2999999999999999889 0.2999999999999999889 0 0 1 8 11.699999999999999289
L8 11.300000000000000711
A0.2999999999999999889 0.2999999999999999889 0 0 0 7.7000000000000001776 11
L7.2999999999999998224 11
A0.2999999999999999889 0.2999999999999999889 0 0 1 7 10.699999999999999289
L7 10.300000000000000711
A0.2999999999999999889 0.2999999999999999889 0 0 0 6.7000000000000001776 10
L6.2999999999999998224 10
A0.2999999999999999889 0.2999999999999999889 0 0 1 6 9.6999999999999992895
L6 9.3000000000000007105
A0.2999999999999999889 0.2999999999999999889 0 0 1 6.2999999999999998224 9
L6.7000000000000001776 9i
A0.2999999999999999889 0.2999999999999999889 0 0 0 7 8.699999999999999

for 50 qr codes its generating only 2 qr codes i have used errorCOrrection('M') for generating
