### ISSUE TITLE
Generate QR Code with transparent background

### ISSUE THREAD

**Issue by vkiranmaniya** [SimpleSoftwareIO/simple-qrcode#172]
I tried using backgroundColor(255, 0, 0, 0); but it's seems not working. How to generate svg QRCode with transparent background?

**Comment by ZBrettonYe** [comment]
You should really read the documents!!  Here is the link https://www.simplesoftware.io/#/docs/simple-qrcode

`QrCode::backgroundColor(255, 0, 0, 25); //Red background QrCode with 25% transparency `

The 4th parameter tells the percentage of transparency
