### ISSUE TITLE
Email Invalid Format

### ISSUE THREAD

**Issue by GenedyMohamed** [SimpleSoftwareIO/simple-qrcode#173]
Shows plus instead of spaces in for subject and body on some or most phones.
On huawei phone camera it opens correctly on outlook app but does not show body and subject on gmail app. Using 3rd party app works on gmail also though.

$attrs = $user_qrcode->attributes()->get();
$qrcode_content = $qrcode->email($attrs[0]->value, $attrs[1]->value, $attrs[2]->value);

**Comment by SimplyCorey** [comment]
Unfortunately, there isn't much I can do to force these phones to accept a formatted QrCode.  There might be a better separator that can be used that has wider support.  Currently `body` and `subject` are used to build the QrCode.

I'll reopen this if you can provide some screenshots of what you are seeing and some suggestions for better separators.
