### ISSUE TITLE
Do not explicitly require bacon-qr-code 2.0.0

### ISSUE THREAD

**Issue by Tklaversma** [SimpleSoftwareIO/simple-qrcode#175]
By explicitly requiring ```"bacon/bacon-qr-code": "2.0.0"``` instead of ```"bacon/bacon-qr-code": "^2.0"``` I get an error when also requiring other packages that has ```bacon-qr-code``` as a dependecy.

As a workaround I now directly depend on ```bacon-qr-code 2.0.0``` in my own project.

Could you update the ```composer.json``` to use ```"bacon/bacon-qr-code": "^2.0"``` please? This way people can remove the explicit require of this package in their own projects.

**Comment by SimplyCorey** [comment]
@Tklaversma This makes sense and was a mistake on my part.  Thanks for reporting.

**Comment by Tklaversma** [comment]
> @Tklaversma This makes sense and was a mistake on my part. Thanks for reporting.

No worries. Glad you're picking it up!
When can we expect the update?

**Comment by Tklaversma** [comment]
@SimplyCorey No worries. Glad you're picking it up! When can we expect the update?

**Comment by SimplyCorey** [comment]
Something should go out this week.  I have some other issues I want to wrap up in this next release.

**Comment by SimplyCorey** [comment]
This is within 3.0.1.
