### ISSUE TITLE
Image result black and white with size 200

### ISSUE THREAD

**Issue by trinhcanhphuc** [SimpleSoftwareIO/simple-qrcode#176]
Result image return black and white logo when I merge with this logo: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/320/google/110/third-place-medal_1f949.png

**Comment by SimplyCorey** [comment]
Can I get a full code sample please?

**Comment by trinhcanhphuc** [comment]
$qrcode->format('png')->merge($this->data['logo'], 0.3, true)
        ->size(500)->errorCorrection('H')
        ->color($fore_color[0], $fore_color[1], $fore_color[2])
        ->backgroundColor($back_color[0], $back_color[1], $back_color[2])
        ->encoding('UTF-8')
        ->generate($content, $this->get_qr_images_path());


Yes, this is my code $this->data['logo'] is base64 image encode, $content is as a string and get_qr_images_path is a qr result path

**Comment by SimplyCorey** [comment]
I can not reproduce this.  Please reopen if this continues on 3.0.1

**Comment by trinhcanhphuc** [comment]
Thanks, let me check
