### ISSUE TITLE
Interface 'Illuminate\Contracts\Support\DeferrableProvider' not found

### ISSUE THREAD

**Issue by Iamnameless** [SimpleSoftwareIO/simple-qrcode#177]

**Comment by lybuneiv** [comment]
Pls help I also get this error

**Comment by ssistemas** [comment]
compatible only with version > = 5.8 :

**Comment by SimplyCorey** [comment]
V3 only supports Laravel 5.8 and above.  You can use the old v2 if you need support on these.

**Comment by SimplyCorey** [comment]
https://github.com/SimpleSoftwareIO/simple-qrcode/tree/v2
