### ISSUE TITLE
QrCode facade confusing and probably requires documentation adjustments

### ISSUE THREAD

**Issue by rreynier** [SimpleSoftwareIO/simple-qrcode#178]
The documentation directs us to simply use: `QrCode::generate('Make me into a QrCode!')` without mention of a `use` statement. This does not work in a controller for example.

There does not appear to be a facade called QrCode either. 

After some poking around I did find a file literally called `Facade` which does work by simply importing `SimpleSoftwareIO\QrCode\Facade` which then allows me to do something like `Facade::generate...` in my controller. 

Alternatively I could update the use statement to look something like `use SimpleSoftwareIO\QrCode\Facade as QrCode;` which then allows me to use it as directed in the documentation. 

So my question is, what is the intention here? Is the documentation simply outdated? Maybe I am doing something wrong? 

Thanks!

**Comment by SimplyCorey** [comment]
This was a mistake on my part when I made some code changes on v3.  I am going to revert to the v2 way of this to resolve these issues.

**Comment by SimplyCorey** [comment]
I've addressed this in the new release today.  Originally, I was going to release 3.0.1 to fix this and some other bugs but the change has the possibility to be backwards breaking so v4 is being released.  I've also added a statement to the docs to pull in the facade correctly.

**Comment by rreynier** [comment]
Thank you!
