### ISSUE TITLE
return instance of HtmlString

### ISSUE THREAD

**Issue by benjamindoe** [SimpleSoftwareIO/simple-qrcode#182]
Hi, 

Have you considered returning the QR string as an instance of `Illuminate\Support\HtmlString`? It would mean you don't need to do `{!! $qrString !!}` but instead `{{ $qrString }}`

**Comment by benjamindoe** [comment]
Happy to implement this if PR would be accepted. Can make it possible to only return `HtmlString` instance if `illumiante\support` is installed

**Comment by SimplyCorey** [comment]
I would accept a PR for this.

**Comment by benjamindoe** [comment]
Beat me to it!
