### ISSUE TITLE
I get a err like "Interface 'Illuminate\Contracts\Support\DeferrableProvider' not found" in laravel 5.7 

### ISSUE THREAD

**Issue by koko-e** [SimpleSoftwareIO/simple-qrcode#184]
Hello ,

when I try to upgrade 2.0 to 3.0 at laravel 5.7 , I get this error
"Interface 'Illuminate\Contracts\Support\DeferrableProvider' not found"
how i can fix it , please? do I need to upgrade laravel to 5.8 or only this way ?

**Comment by SamuelNitsche** [comment]
I think version 3 requires laravel 5.8 or later.

@SimplyCorey Wouldn't it make sense to add version constraints for laravel in the `composer.json` file?

**Comment by koko-e** [comment]
@SamuelNitsche 
Thank you , I think you are right , I fixed it  after  upgrate laravel 5.7 to 5.8 .
but it is better if ver2 can still download and use after ver3 released.

**Comment by SimplyCorey** [comment]
version 2 is still available for use.  There's a known issue with the service provider changed in v3.  I'm debating on how to fix the issue without causing a breaking change.

**Comment by SimplyCorey** [comment]
This should be fixed in 3.0.1 shipping later today.
