### ISSUE TITLE
Size in percentage 

### ISSUE THREAD

**Issue by sagadsalem** [SimpleSoftwareIO/simple-qrcode#187]
I want to make the size of the SVG QR to 80% for example
but the size function accepts only numeric values
any ideas

**Comment by SamuelNitsche** [comment]
This doesn't really make sense. You cannot just create something with a size of 80% of _something_. What do you really try to achieve?

**Comment by sagadsalem** [comment]
why not making sence?
if i have responsive site then the size will not work proply form me

**Comment by SamuelNitsche** [comment]
You should create the qr code as svg so you can make it responsive.

**Comment by sagadsalem** [comment]
I always format qr as SVG but still i cant size it the qr still not responsive

**Comment by SimplyCorey** [comment]
This isn't really supported.  I would suggest making your qrcode at a fixed width (250 pixels) for example and then using CSS to scale the qrcode to fix 80% of whatever container you need to put the qrcode into.
