### ISSUE TITLE
One line code is not correct for Laravel 5.1.16 (LTS)

### ISSUE THREAD

**Issue by mclxly** [SimpleSoftwareIO/simple-qrcode#19]
Today I'm trying to use this great lib and encounter an error(500).

I changed following code and then it works nice.
{{ QrCode::size(100)->generate(Request::url()); }}
to:
{!! QrCode::size(200)->generate(Request::url()) !!}

Hope it helps.

**Comment by SimplyCorey** [comment]
This depends on which Laravel version you are using.  Laravel 5 changed the syntax to escape output and therefore escapes the SVG output.

**Comment by SimplyCorey** [comment]
Adjusted examples to Laravel 5 syntax.
