### ISSUE TITLE
Is the Eye Shape(circle) really look like this?

### ISSUE THREAD

**Issue by psycrow117** [SimpleSoftwareIO/simple-qrcode#197]
Hello!
I just wanna know if its intended that the eye shape "circle" should be really like that? 
![image](https://user-images.githubusercontent.com/1185466/95058444-1f4b9500-072a-11eb-849f-9f363e0ef473.png)

instead of 

![image](https://user-images.githubusercontent.com/1185466/95058511-38ecdc80-072a-11eb-81ee-5cb022a2b367.png)

Thanks!

**Comment by SimplyCorey** [comment]
That is the correct eye shape.
