### ISSUE TITLE
How to change eye frame shape(curved square, square)

### ISSUE THREAD

**Issue by psycrow117** [SimpleSoftwareIO/simple-qrcode#198]
Hi,

I just saw a sample test on this [link](https://github.com/SimpleSoftwareIO/simple-qrcode/issues/171#issuecomment-703105079) and I'm curious if is it possible to have a different eye frame shape(curved square, square) right now to do? and how? 

Here is the image I saw from the link
![image](https://user-images.githubusercontent.com/1185466/95066120-8c642800-0734-11eb-91e5-68ac9428a917.png)

Thank you.

**Comment by SimplyCorey** [comment]
There is a method called `eyeStyle` which can change the eyes.  There is two acceptable styles currently, `circle` and `square`.  The eyes are slightly changed based upon which overall style is being used.  There is more information in the docs.  https://www.simplesoftware.io/#/docs/simple-qrcode

![image](https://user-images.githubusercontent.com/624784/95071715-1b8f2280-06d8-11eb-9e0d-5c24a0d64b78.png)
![image](https://user-images.githubusercontent.com/624784/95071684-1205ba80-06d8-11eb-8c88-f2b571cf7a25.png)

**Comment by insology** [comment]
There in issue on the docs, the method is not "eyeStyle" but just "eye".

**Comment by SimplyCorey** [comment]
Addressed in docs.
