### ISSUE TITLE
Margin not working correctly

### ISSUE THREAD

**Issue by chrisrollins65** [SimpleSoftwareIO/simple-qrcode#2]
If I use margin(0), it gives me the same thing as margin(1) and margin(2). Then if I do margin(3) it gives me the same thing all the way up to margin(10).

Anyway, margin(0) is good enough for me but I thought I'd point this out. Thanks for the good work!

**Comment by ctf0** [comment]
@SimplyCorey could u also post the formula or how the margin gets calculated ?

**Comment by SimplyCorey** [comment]
@ctf0 If you look at a QrCode, it is made up of a bunch of black and white squares with a constant about of squares per row depending on the version.  For example, version 1 has 21x21, version 2 has 25x25.  See: http://en.wikipedia.org/wiki/QR_code#Storage

The QrCode generator will change the size of the squares to ensure that the output is equal to the size provided.  If you want a QrCode that is 500 pixels tall/wide you would use size(500) and the QrCode generator would calculate the size of the squares to ensure that there is still 21x21 (version 1) blocks.  A margin(1) would "add" 1 block of squares around the QrCode and fill it with white space.  The generator would then recalculate the size of the blocks to ensure that there is still 21x21 (version 1) blocks.

You can see a good example of this by running the following and comparing them:

    {{QrCode::size(500)->margin(0)->generate("Hello World!")}}
    {{QrCode::size(500)->margin(1)->generate("Hello World!")}}
    {{QrCode::size(500)->margin(2)->generate("Hello World!")}}
    {{QrCode::size(500)->margin(3)->generate("Hello World!")}}

Margin 0
![0](https://cloud.githubusercontent.com/assets/624784/5608318/5ca9d880-944e-11e4-85cb-c31acec194ba.png)

Margin 1
![1](https://cloud.githubusercontent.com/assets/624784/5608319/5da0ad0e-944e-11e4-9b91-7639ce0f6c22.png)

Margin 2
![2](https://cloud.githubusercontent.com/assets/624784/5608320/6091d538-944e-11e4-9ae9-72666b9cfd18.png)

Margin 3
![3](https://cloud.githubusercontent.com/assets/624784/5608321/61bfd5d6-944e-11e4-9f4a-04c3e4239bee.png)


These are all the same QrCodes with a different margin. Basically, each margin adds 1 more row/column to the outside of the QrCode version and then the generator makes adjustments to keep the size the same.  Does that make sense?  I can not really think of a good way to word this.  If you can, can you please make a pull request and update the docs?

**Comment by ctf0** [comment]
yeah it makes a perfect sense ,so basically u make any size and the gen will add a 1,2,3,etc.. row from each side to make a perfect square and without getting pixelated when outputing as png.
