### ISSUE TITLE
->size() breaks merge()

### ISSUE THREAD

**Issue by branall1** [SimpleSoftwareIO/simple-qrcode#20]
It appears if I attempt to use size() either before or after the merge method in a chain - the image is not merged.

Example:
`<img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge('/public/tiny-green.png',.3)->size(190)->generate($url)) !!}">`

QR code generates properly - but without the merged image. (http://goo.gl/ImyLlm)

If you remove size - it generates the code like a boss, complete with merged image (http://goo.gl/dlZGgi)

**Comment by SimplyCorey** [comment]
Thank you for reporting this bug.  Try running the size method before the merge method.  This is a bug we will fix in the next release!

**Comment by branall1** [comment]
That was pretty much the first thing I tried. I didn't want to bother anyone with a bug report without attempting to resolve it on my own. I tried size() at the beginning, right before merge, right after, etc. The only way merge would work was without size.

I was wanting to take a look and see if I can squash this one on my own and send you guys a pull - but time has not been on my side. I doubt we will ultimately use merge for this project - I was just playing around with it when I ran into the issue with size().

Thank you very much for the follow up - if you need anything else from me please let me know.

**Comment by SimplyCorey** [comment]
Hmm.  I must have missed this when testing!  I'll try to get a bug fix out in the next few days.  Thanks again for the report!

**Comment by SimplyCorey** [comment]
Fixed in 1.3.1 :wink:
