### ISSUE TITLE
Error Message "Unable to set image format" when is format('png')

### ISSUE THREAD

**Issue by croxarens** [SimpleSoftwareIO/simple-qrcode#203]
Hi!

I'd like to serve a QR code as a file, so I guess the best optionis PNG.

When I run the following code
```
$image = \QrCode::format('png')
            ->size(300)->errorCorrection('H')
            ->generate('A simple example of QR code!');
```
I get an "Unable to set image format" message coming from
```
Imagick::setimageformat
vendor/bacon/bacon-qr-code/src/Renderer/Image/ImagickImageBackEnd.php:75
```

The library is working fine with 

`QrCode::size(200)->generate('here a message')`

It's returning a SVG code in the page.

Any help, suggestion?

**Comment by SimplyCorey** [comment]
What version are you using?

**Comment by croxarens** [comment]
Yes, you were right. I just discover the php module php7-pecl-imagick is not forcing the system in installing the imagemagick software. After manually installing it, I now have a section in phpinfo with all supported format.

Thanks so much @SimplyCorey
