### ISSUE TITLE
Breaking change in 4.1 - returns instance of Illuminate\Support\HtmlString

### ISSUE THREAD

**Issue by DarrenChowles** [SimpleSoftwareIO/simple-qrcode#205]
I noticed after updating from 4.0 to 4.1, the Generator now returns an instance of `Illuminate\Support\HtmlString` rather than a string. 

https://github.com/SimpleSoftwareIO/simple-qrcode/commit/3b721089cc541f6c37f0a41b90377529af977948#diff-4ee5eaad222ef0782fccd29473a5f1860988b7cf91cdcd0a12628b2377972b36L165

Luckily the "fix" is simply casting this to a string:

```php
$var = (string)QrCode::format('svg')->margin(0)->size(200)->generate($inlineUrl);
```

Hopefully this helps anybody experiencing this issue after updating.

**Comment by SimplyCorey** [comment]
My apologies, this one slipped by me.  I think it's too late to reverse the change but I'll get something added to the docs.

**Comment by SimplyCorey** [comment]
Added a note into the docs.

**Comment by felixkaleke** [comment]
$qr=(string)QrCode::size(500)
            ->email('admin@example.com', 'Welcome to Coding driver!.', 'ggfrgrfgrfgrfgrfgrfgrfgrfg')
            ->generate('codingdriver.com', public_path("images/staffidqrcode/qrcode.png"));


I tried the above code but not working , the objective of the qr code was to read email and phonenumber and sms all together , please share your results for the answers to the above problem

**Comment by acydh** [comment]
> $qr=(string)QrCode::size(500) ->email('[admin@example.com](mailto:admin@example.com)', 'Welcome to Coding driver!.', 'ggfrgrfgrfgrfgrfgrfgrfgrfg') ->generate('codingdriver.com', public_path("images/staffidqrcode/qrcode.png"));
> 
> I tried the above code but not working , the objective of the qr code was to read email and phonenumber and sms all together , please share your results for the answers to the above problem

That's probably because you're exporting a png instead of working with svg

**Comment by vasusharma123** [comment]
Class "SimpleSoftwareIO\QrCode\QrCodeServiceProvider" not found

**Comment by sawal123** [comment]
In PackageDiscoveryTrait.php line 317:

  Package simplesoftwareio/simple-qrcode has requirements incompatible w
  ith your PHP version, PHP extensions and Composer version:
    - simplesoftwareio/simple-qrcode 4.2.0 requires ext-gd * but it is n
  ot present.

**Comment by ElvisCode110423** [comment]
Tengo la versión 4.2 composer require simplesoftwareio/simple-qrcode clase no encontrada usando laravel 10
