### ISSUE TITLE
Is it possible to generate current time utc 

### ISSUE THREAD

**Issue by ap-coder** [SimpleSoftwareIO/simple-qrcode#207]
Just wondering if it has this capability?
Maybe something like:
```
QrCode::utc();
```
And date 
```
QrCode::date('current');
```
Also can we put a custom array of data into it and if so what would that formatting look like?
```
QrCode::custom(['red' => 21, 'blue' => 40, 'message' => 'Make me into a QrCode!']);
```

thnx

**Comment by SimplyCorey** [comment]
What is the use case here?  Wouldn't `QrCode::generate(now());` cover your use case?
