### ISSUE TITLE
Error Message "Unable to set image format" when is format('png') 

### ISSUE THREAD

**Issue by bird-c** [SimpleSoftwareIO/simple-qrcode#208]
Hi, Good day!

im getting this error, Error Message "Unable to set image format" when is format('png') 
my php version
![image](https://user-images.githubusercontent.com/69282512/97937183-e2ba9a00-1db8-11eb-871c-1c11a63b301a.png)

with imagick installed
![image](https://user-images.githubusercontent.com/69282512/97937161-d33b5100-1db8-11eb-9b88-aeac74cda6e8.png)

is it because of the versions?

Thank you and Godbless

**Comment by acecx** [comment]
how to fixed?

**Comment by bird-c** [comment]
> how to fixed?

i just used jpg format instead of png format

**Comment by SimplyCorey** [comment]
Can you provide a code example of what you ran?

**Comment by vonericf** [comment]
> Can you provide a code example of what you ran?

Hi this is what im trying to do, i want to add logo on the QR Code, heres the code

data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(200)->merge( '/public/admin-assets/img/logo.png' )->color(0,0,0)->backgroundColor(255,255,255)->generate(''.(isset($user->qrcode->qrcode) ? $user->qrcode->qrcode : 'QR Unavailable).'')) !!}

**Comment by songlen** [comment]
similar problem !
php7.2

**Comment by subdesign** [comment]
same problem here, explanation in this issue:
https://github.com/Bacon/BaconQrCode/issues/142

any idea?

simple-qrcode v4.2.0

**Comment by MarioCohuo** [comment]
En mi caso, tuve el mismo problema hace dos días con la librería simple-qrcode v4 y solo actualice con composer update la librería Bacon, y se solvento el problema.

**Comment by danielmrdev** [comment]
> En mi caso, tuve el mismo problema hace dos días con la librería simple-qrcode v4 y solo actualice con composer update la librería Bacon, y se solvento el problema.

@MarioCohuo, how do you do that? 
I have same issue, but `composer update bacon/bacon-qr-code:^3.0` give me errors because `simple-qrcode`is locked to v.2.0
