### ISSUE TITLE
Sending QR code as email?

### ISSUE THREAD

**Issue by mikt** [SimpleSoftwareIO/simple-qrcode#21]
Hi,

I'm trying to send the QR code as an email, but it simply doesn't display in the email client.
I have tried both gmail and yahoo.

To display the image I use
```<img src="data:image/png;base64, {{ base64_encode($qr) }} ">```

To send the email I use the following:
```
$qr = QrCode::format('png')->size(200)->generate('http://google.com');
                Mail::send(
                    'emails.product_redeem',
                    [
                        'account' => $product->user,
                        'product' => $product,
                        'qr' => $qr
                    ],
                    function ($m) use ($product) {
                        $m->to($product->user->email, $product->user->username)
                            ->subject('Prospector theater - Redeem product')
                            ->from('no-reply@prospectortheater.org', 'Prospector theater');

                    }
                );
```

I'm using Laravel 5.1 to send the email:
http://laravel.com/docs/5.1/mail

Any idea on how to come around this?

**Comment by SimplyCorey** [comment]
Can I see your emails.product_redeem template please?

**Comment by mikt** [comment]
Sure, thank you:

```
<!DOCTYPE html>
<html>
<head>
    <title>Prospector theater</title>

</head>

<body>
<h3>Hello {{ $account->first_name }} {{ $account->last_name }},</h3>

<p>This email serves as a ticket for a free {{ $product->product->name }}. <br />
    Please bring a printed version of this email with you in order to redeem it on-site.</p>
@if (isset($product->expires))
    <p>Keep in mind that this ticket is only valid till {{ $product->expires }}</p>
@endif

<br />
<br />
<br />
<img src="data:image/png;base64, {{ base64_encode($qr) }} ">
{{--{!! $qr !!}--}}

<p>Thank you,</p>
<br />
<p>Prospector theater</p>
</body>
</html>
```

**Comment by SimplyCorey** [comment]
Change

    <img src="data:image/png;base64, {{ base64_encode($qr) }} ">

to

    <img src="{!!$message->embedData($qr, 'QrCode.png', 'image/png')!!}">

I just tested this and it works in gmail/inbox.  Please let me know if you have any other issues!

**Comment by plcosta** [comment]
@SimplyCorey It works fine for me. Thanks!

**Comment by SimplyCorey** [comment]
Added to readme.

**Comment by putupadang** [comment]
> Change
> 
> ```
> <img src="data:image/png;base64, {{ base64_encode($qr) }} ">
> ```
> 
> to
> 
> ```
> <img src="{!!$message->embedData($qr, 'QrCode.png', 'image/png')!!}">
> ```
> 
> I just tested this and it works in gmail/inbox. Please let me know if you have any other issues!

what thats mean the $message variable ?

**Comment by revroad-dev** [comment]
This still doesn't work for me. Copied it exactly as is.

**Comment by SimplyCorey** [comment]
@revroad-dev It's possible that gmail has changed something on their end.  Can you paste an example of a raw email in here please?

**Comment by crassclown** [comment]
> @revroad-dev It's possible that gmail has changed something on their end. Can you paste an example of a raw email in here please?

I get an empty `<img>` tag as well

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Email</title>
</head>
<body>
    <p>
        Dear, {{ $karyawan->nama }}
        <br><br>
        Berikut QR Code yang bisa anda gunakan untuk absensi:<br>
        <img src="{!!$message->embedData(QrCode::format('svg')->generate($karyawan->id_karyawan), 'QrCode.svg', 'image/svg+xml')!!}">
    </p>
</body>
</html>
```

**Comment by PoojaJadav** [comment]
> ```
> <img src="{!!$message->embedData($qr, 'QrCode.png', 'image/png')!!}">
> ```

What is the $message here?

**Comment by muarachmann** [comment]
> > ```
> > <img src="{!!$message->embedData($qr, 'QrCode.png', 'image/png')!!}">
> > ```
> 
> What is the $message here?

If you use laravel https://laravel.com/docs/8.x/mail#inline-attachments
