### ISSUE TITLE
merge() completely transparent logo covers the QR code

### ISSUE THREAD

**Issue by pekineseZ** [SimpleSoftwareIO/simple-qrcode#210]
I'm unsure if there's an existing issue for this, when using a logo like:

        $imageString = QrCode::size(200)->format('png')
        ->merge(storage_path('logoQR.png'), .5, true)

Logo used:
![logoQR](https://user-images.githubusercontent.com/23654590/99533385-19da9f00-29a6-11eb-9aea-74f44f4dc32a.png)

The resulting QR code will not respect the transparent logo:
![qrCode](https://user-images.githubusercontent.com/23654590/99533473-3d9de500-29a6-11eb-9fa6-735d212d4ba4.png)

Any ideas how to fix this / is this currently known as issue?

**Comment by muarachmann** [comment]
@pekineseZ #201 should fix this. If you are in a hurry, you can apply that patch on your branch.

**Comment by prom00** [comment]
> @pekineseZ #201 should fix this. If you are in a hurry, you can apply that patch on your branch.

I've changed the 2 files locally, I can confirm this works like a charm!
Thank you for the fix.

**Comment by SimplyCorey** [comment]
Thanks guys, Ill work on getting this merged and versioned up this weekend.

**Comment by JexPY** [comment]
Got same problem only after updating to version 4.1.0, waiting for update ✌️🤞

**Comment by SimplyCorey** [comment]
Should be fixed in the new version about to go out.
