### ISSUE TITLE
error when generate image

### ISSUE THREAD

**Issue by ahmedbondok2006** [SimpleSoftwareIO/simple-qrcode#213]
ErrorException
imagecreatefromstring(): Data is not in a recognized format
i have this error when making this code

    public function imageQrCode()
    {
          $image = QrCode::format('png')
          ->merge(public_path('website/images/barcode.png'), 0.5, true)
          ->size(500)
          ->generate('A simple example of QR code!');
          return response($image)->header('Content-type','image/png');
    }

i need to send qr code within email

**Comment by SimplyCorey** [comment]
Not sure what is going on here.  Are you using a correctly formatted png file?  Does this work with `mergeString` in binary format?
