### ISSUE TITLE
Can't generate qr code for custom uri schema?

### ISSUE THREAD

**Issue by ghost** [SimpleSoftwareIO/simple-qrcode#220]
Tried generating a qr code for the following uri:
```
myapp://test?key=value
```

But when reading the qr code only the `myapp` part is being read.
Please let me know if there are any settings is missing or what I'm trying to do is wrong somehow?

**Comment by SimplyCorey** [comment]
This would depend on the QR code reader that you are using.  I would try any other reader.

**Comment by ghost** [comment]
I tried multiple readers but still the same result of only the `myapp` part being read.
In the end we "solved" it by url encode the whole uri.. would be curious if anyone else could confirm this?

**Comment by SimplyCorey** [comment]
@chwiz143 Interesting.  Can you provide a code example and I can look at it more.
