### ISSUE TITLE
Add more style of QR Code

### ISSUE THREAD

**Issue by mzee19** [SimpleSoftwareIO/simple-qrcode#221]
![image](https://user-images.githubusercontent.com/72722281/111298792-fd5b2480-8670-11eb-8d6a-926d287c3be8.png)

![image](https://user-images.githubusercontent.com/72722281/111423065-87f36080-8711-11eb-95da-e56d7eae36c1.png)

Here is only three style available and only two eyes available but I want more than these.

**Comment by SimplyCorey** [comment]
Free free to make a PR.
