### ISSUE TITLE
SMS QR code is not work

### ISSUE THREAD

**Issue by mzeeshan455** [SimpleSoftwareIO/simple-qrcode#222]
QR code is not scannable when second parameter (message) is pass in SMS Helper.

**Comment by SimplyCorey** [comment]
What did you use to make the QrCode?  Which scanner?

**Comment by mzeeshan455** [comment]
use Samsung (Mobile`s camera) for the scanning purpose, no use any other apps

**Comment by SimplyCorey** [comment]
This works on iOS.  Feel free to make a PR.
