### ISSUE TITLE
VCard not work properly

### ISSUE THREAD

**Issue by mzeeshan455** [SimpleSoftwareIO/simple-qrcode#224]
After scanning , data not send. return empty data
Or send me the right way for QR Code
I am trying this 
    {!! QrCode::encoding('UTF-8')->eye('square')->style('square')->size(300)->generate('BEGIN:VCARD VERSION:4.0 N:Gump;Forrest;;Mr.; FN:Forrest Gump ORG:Bubba Gump Shrimp Co. TITLE:Shrimp Man PHOTO;MEDIATYPE=image/gif:http://www.example.com/dir_photos/my_photo.gif TEL;TYPE=work,voice;VALUE=uri:tel:+1-111-555-1212 TEL;TYPE=home,voice;VALUE=uri:tel:+1-404-555-1212 ADR;TYPE=WORK;PREF=1;LABEL="100 Waters Edge\nBaytown\, LA 30314\nUnited States of America":;;100 Waters Edge;Baytown;LA;30314;United States of America ADR;TYPE=HOME;LABEL="42 Plantation St.\nBaytown\, LA 30314\nUnited States of America":;;42 Plantation St.;Baytown;LA;30314;United States of America EMAIL:forrestgump@example.com REV:20080424T195243Z x-qq:21588891 END:VCARD'); !!}

**Comment by alexv96** [comment]
Were you able to make it work?
