### ISSUE TITLE
How can i set a logo in the qrcode?

### ISSUE THREAD

**Issue by Bantes** [SimpleSoftwareIO/simple-qrcode#23]
like this qrcode

https://github.com/SimpleSoftwareIO/simple-qrcode/raw/master/docs/imgs/merged-qrcode.png?raw=true

thanks

**Comment by SimplyCorey** [comment]
QrCode::format('png')->merge('path-to-image.png')->generate('QrCode Here');

**Comment by Bantes** [comment]
thanks for your reply.
