### ISSUE TITLE
responsive size

### ISSUE THREAD

**Issue by zebamba** [SimpleSoftwareIO/simple-qrcode#230]
The size generates HTML width and height, the problem is image is not responsive.

Would be possible to set size in a way to be responsive?

**Comment by SimplyCorey** [comment]
The SVG should be responsive.  How are you making the qrcodes?

**Comment by youmustwearface** [comment]
Issue is a hardcoded width="100" and height="100" in the svg element.

**Comment by zebamba** [comment]
I am generating the QR code following the docs instructions.

```php
    {!! QrCode::size(300)->generate($url); !!}
```

@youmustwearface stated the issue is the hardcoded HTML attribute.

**Comment by SimplyCorey** [comment]
Feel free to open a PR.
