### ISSUE TITLE
<?"0.1="version xml 8-UTF="encoding?" >

### ISSUE THREAD

**Issue by Ammar09** [SimpleSoftwareIO/simple-qrcode#231]
![Capture](https://user-images.githubusercontent.com/14530968/116075501-b3b41f80-a69b-11eb-9cb3-a4f1b599c260.PNG)

Hello everyone,

I am trying to generate QRcdoe on PDF file but it shows
 (<?"0.1="version XML 8-UTF="encoding?">) above the QRcode
as it is shown in the attachment

**Comment by kabowo** [comment]
Same here

**Comment by kabowo** [comment]
Try to generate with format png

**Comment by SimplyCorey** [comment]
I can't reproduce this.  Please provide a full code example and the output of the svg.

**Comment by CovertError** [comment]
any ideas for ways to get around this issue without using png
