### ISSUE TITLE
Self Signed CERT error

### ISSUE THREAD

**Issue by ben007zxbaj** [SimpleSoftwareIO/simple-qrcode#233]
can we have additional Options for the file_get_contents

class Generator
{

    public function merge(string $filepath, float $percentage = .2, bool $absolute = false): self
    {
        if (function_exists('base_path') && ! $absolute) {
            $filepath = base_path().$filepath;
        }
		
		$arrContextOptions=array(
			"ssl"=>array(
				"verify_peer"=>false,
				"verify_peer_name"=>false,
			),
		);  

        $this->imageMerge = file_get_contents($filepath, false, stream_context_create($arrContextOptions));
        $this->imagePercentage = $percentage;

        return $this;
    }

**Comment by SimplyCorey** [comment]
I think you could load the image how ever you wanted and then use `mergeString` using the binary string.  Would this work?
