### ISSUE TITLE
PNG base64_encode return empty image

### ISSUE THREAD

**Issue by Cristiano1103** [SimpleSoftwareIO/simple-qrcode#235]
Hello! 

i use this to generate:
`<img src="data:image/png;base64, {{ base64_encode(QrCode::encoding('UTF-8')->format('png')->margin(1)->size(220)->generate('Test')) }}">
`

but returns a transparent image.

i using laravel 8 and php 7.4

**Comment by SimplyCorey** [comment]
This code works for me.  You will need to provide more information if this is still an issue.

**Comment by Cristiano1103** [comment]
I fixed by updating  imagick extension :)
