### ISSUE TITLE
Any examples with VCARD?

### ISSUE THREAD

**Issue by alexv96** [SimpleSoftwareIO/simple-qrcode#237]
I was looking at the documentation but when using VCARD it's not clear to me how to use it and the example is a page that takes me to wikipedia. 

Would it be something like this?
```
{!! QrCode::size(100)->generate('BEGIN:VCARD:name'); !!} //Not work name
```

**Comment by MattiaMarchiorato** [comment]
Hello @alexv96 
'BEGIN:VCARD:name' is not a valid format like:

BEGIN:VCARD
VERSION:2.1
N:Mao Zett
EMAIL:mao@zett.it
ORG:Acme S.r.l.
TITLE:Sales trader
ADR:Via Inglesina, Milano
URL:http://www.deji.eu
TEL;HOME;VOICE:+39 (389) 2323232 2323
TEL;WORK;VOICE:+39 (389) 2323232 2323
END:VCARD

**Comment by SimplyCorey** [comment]
@Mattia-Marchiorato Is correct here.  You would need to input the entire vcard standard.  You can use something like https://vcardmaker.com/.  

If anyone wants to make a helper for this library, I would appreciate and accept the PR.

**Comment by MattiaMarchiorato** [comment]
@SimplyCorey we are using an helper in our project, maybe we can create a PR adding the helper.

**Comment by SimplyCorey** [comment]
@Mattia-Marchiorato thst would be amazing.  Thank you
