### ISSUE TITLE
how to insert new line 

### ISSUE THREAD

**Issue by support-softya** [SimpleSoftwareIO/simple-qrcode#240]
hi im using this with laravel 8 
and im wondering how to insert new line like this .. 
` {{ QrCode::size(200)->encoding('UTF-8')->generate(
                                                        'رقم الفاتورة' . $journal_entry['number'] . 'Invoice number'.
                                                        '<br />'.
                                                        'تاريخ الاصدار' . $journal_entry['date'] . 'Issue Date'.
                                                        '<br />'.
                                                        'العميل' . $branch['name'] . 'Customer'.
                                                        '<br />'.
                                                        'رقم القيمة المضافة للعميل' . $branch['tax_id'] . 'Customer'.
                                                        '<br />'.
                                                        'عنوان العميل' . $branch['address'] . 'Customer Address'.
                                                        '<br />'.
                                                        'المورد' . $user['name'] . 'Buyer'.
                                                        '<br />'.
                                                        'رقم القيمة المضافة للمورد' . $user['tax_id'] . 'Buyer'.
                                                        '<br />'.
                                                        'عنوان المورد' . $user['address'] . 'Customer Address'
                                                    ) }}`
thanks

**Comment by SimplyCorey** [comment]
I believe this is going to depend on the device reading the qrcode.  You might be able to try `\n` or `\r\n` but I'm unsure if this will work.
