### ISSUE TITLE
Possible to remove half dots

### ISSUE THREAD

**Issue by gitleif** [SimpleSoftwareIO/simple-qrcode#242]
Behind the merged center image there should be possible to completly remove the dots that are not completely visible. See attached image.
![suggestion](https://user-images.githubusercontent.com/26165143/145088293-82e22b90-0c30-446f-9ef8-00f641b4b503.png)

**Comment by SimplyCorey** [comment]
Not currently, but I'd accept a PR that could better center the image.

**Comment by SimplyCorey** [comment]
Closing as a duplicate of https://github.com/SimpleSoftwareIO/simple-qrcode/issues/192
