### ISSUE TITLE
Problem with gradient, eyeColor, style

### ISSUE THREAD

**Issue by d13moroy** [SimpleSoftwareIO/simple-qrcode#245]
I have this code, i follow documentation, but always i get error whit eyeColor, gradient and style, when i comment this 3 options Qr generates ok.

  QrCode::format('png')
            
            ->color($colorRed, $colorGreen, $colorBlue)
            ->backgroundColor($bgColorRed, $bgColorGreen, $bgColorBlue)
            ->eyeColor(1, 0, 204, 153, 0, 153, 119)
            ->gradient(100,100,55,100,100,255,'horizontal')
            ->style('round', 0.9)
            ->size(500)
            ->errorCorrection('H')
            ->generate($url.$idEncuesta.'/QR', $ruta);    

BadMethodCallException:  in file C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php on line 269

#0 C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php(250): SimpleSoftwareIO\QrCode\BaconQrCodeGenerator-&gt;**createClass('eyeColor')**
#1 C:\laragon\www\empati\app\Http\Controllers\QrController.php(107): SimpleSoftwareIO\QrCode\BaconQrCodeGenerator-&gt;__call('eyeColor', Array)

when i comment eyeColor the error change to

BadMethodCallException:  in file C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php on line 269

#0 C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php(250): SimpleSoftwareIO\QrCode\BaconQrCodeGenerator-&gt;**createClass('gradient')**

and when comment gradient the error change to
BadMethodCallException:  in file C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php on line 269

#0 C:\laragon\www\empati\vendor\simplesoftwareio\simple-qrcode\src\SimpleSoftwareIO\QrCode\BaconQrCodeGenerator.php(250): SimpleSoftwareIO\QrCode\BaconQrCodeGenerator-&gt;**createClass('style')**

**Comment by gungdarmayuda** [comment]
excuse me, how to fix that problem? i have same issues
