### ISSUE TITLE
adding an option to remove xml decoration 

### ISSUE THREAD

**Issue by CovertError** [SimpleSoftwareIO/simple-qrcode#246]
there is an issue with the xml decoration showing on pdf generators like mpdf  this ticket shows the issue  #231 it would be great to add a way to remove the XML decoration I tried using str_replace that didn't work if you have any ideas or suggestions let me know

**Comment by ali-alharthi** [comment]
You return the QrCode::generate('...') as string as shown [Here](https://github.com/SimpleSoftwareIO/simple-qrcode/issues/205#issue-722516951)

After that just replace `{!! $qr !!}` with the following:
```
<img src="data:image/svg+xml;base64,{{ base64_encode($qr) }}"  alt="QR Code"/>
```

It should work fine!

**Comment by SimplyCorey** [comment]
Closing.  If there is a bug here please open a PR with a fix.
