### ISSUE TITLE
php 8.1.1 ?

### ISSUE THREAD

**Issue by laduniestu** [SimpleSoftwareIO/simple-qrcode#248]
- Root composer.json requires simplesoftwareio/simple-qrcode ^0.0.4@beta -> satisfiable by simplesoftwareio/simple-qrcode[0.0.4-beta].
- simplesoftwareio/simple-qrcode 0.0.4-beta requires bacon/bacon-qr-code 1.0.0 -> found bacon/bacon-qr-code[1.0.0] but the package is fixed to 2.0.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by laduniestu** [comment]
- Root composer.json requires simplesoftwareio/simple-qrcode ^0.0.4@beta -> satisfiable by simplesoftwareio/simple-qrcode[0.0.4-beta].
- simplesoftwareio/simple-qrcode 0.0.4-beta requires bacon/bacon-qr-code 1.0.0 -> found bacon/bacon-qr-code[1.0.0] but the package is fixed to 2.0.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by SimplyCorey** [comment]
Looks like you are using a very old version.  The latest is 4.2.0 and you are pulling on 0.0.4.  

If this is an issue, feel free to open a PR.
