### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by hamzamalik01** [SimpleSoftwareIO/simple-qrcode#249]
Package simplesoftwareio/simple-qrcode at version ~4 has requirements incompatible with your PHP version, PHP extensions and Composer version:

**Comment by SimplyCorey** [comment]
Please take time to make a reasonable attempt when opening issues.  

This is nothing but a copy paste from a command line that gives no details or insight of what is going on.  Not only did you waste your time by giving no information for someone to help you, you have wasted my time having to review this issue and others like it from people who put in zero effort on a free, open source project.

The open source world is a give and take.  Please, give more than take.
