### ISSUE TITLE
S3 Support?

### ISSUE THREAD

**Issue by yansen-tan** [SimpleSoftwareIO/simple-qrcode#25]
Is it possible to upload the QRCode to Amazon S3 without saving to the webserver first?

**Comment by SimplyCorey** [comment]
Currently it must be saved to the local server because it uses file_put_contents().  This may be something we abstract out in the future in favor of Laravel 5's FileSystem.

**Comment by SimplyCorey** [comment]
After some suggestions, this seems outside the scope of this package.  Closing issue.
