### ISSUE TITLE
ImagickException on linux environment

### ISSUE THREAD

**Issue by rpahmadmasri** [SimpleSoftwareIO/simple-qrcode#251]
When I try to generate a QR code with errorCorrection (M,Q,H) with the following command 
QrCode::format('png')->size(300)->errorCorrection('Q')->eye('circle')->style('round')->merge('/resources/img/logo.png', .35)->generate($url, public_path('img/QR/'. $token.'.png'));

I get the following exception

 ImagickException

  too many bezier coordinates `M8 0.25L8 2.75A0.25 0.25 0 0 0 8.25 3L8.75 3A0.25 0.25 0 0 1 9 3.25
L9 4.75A0.25 0.25 0 0 1 8.75 5L8.25 5A0.25 0.25 0 0 0 8 5.25L8 8.75
A0.25 0.25 0 0 0 8.25 9L9.75 9A0.25 0.25 0 0 1 10 9.25L10 9.75
A0.25 0.25 0 0 1 9.75 10L8.25 10A0.25 0.25 0 0 0 8 10.25L8 11.75
A0.25 0.25 0 0 1 7.75 12L6.25 12A0.25 0.25 0 0 1 6 11.75L6 11.25
A0.25 0.25 0 0 1 6.25 11L6.75 11A0.25 0.25 0 0 0 7 10.75L7 10.25
A0.25 0.25 0 0 0 6.75 10L5.25 10A0.25 0.25 0 0 1 5 9.75L5 8.25
A0.25 0.25 0 0 0 4.75 8L2.25 8A0.25 0.25 0 0 0 2 8.25L2 8.75
A0.25 0.25 0 0 1 1.75 9L1.25 9A0.25 0.25 0 0 0 1 9.25L1 10.75
A0.25 0.25 0 0 1 0.75 11L0.25 11A0.25 0.25 0 0 0 0 11.25L0 11.75
A0.25 0.25 0 0 0 0.25 12L0.75 12A0.25 0.25 0 0 1 1 12.25L1 13.75
A0.25 0.25 0 0 1 0.75 14L0.25 14A0.25 0.25 0 0 0 0 14.25L0 27.75
A0.25 0.25 0 0 0 0.25 28L0.75 28A0.25 0.25 0 0 1 1 28.25L1 28.75
A0.25 0.25 0 0 1 0.75 29L0.25 29A0.25 0.25 0 0 0 0 29.25L0 30.75
A0.25 0.25 0 0 0 0.25 31L0.75 31A0.25 0.25 0 0 0 1 30.75L1 29.25
A0.25 0.25 0 0 1 1.25 29L1.75 29A0.25 0.25 0 0 0 2 28.75L2 28.25
A0.25 0.25 0 0 1 2.25 28L2.75 28A0.25 0.25 0 0 0 3 27.75L3 27.25
A0.25 0.25 0 0 0 2.75 27L2.25 27A0.25 0.25 0 0 0 2 27.25L2 27.75
A0.25 0.25 0 0 1 1.75 28L1.25 28A0.25 0.25 0 0 1 1 27.75L1 26.25
A0.25 0.25 0 0 1 1.25 26L1.75 26A0.25 0.25 0 0 0 2 25.75L2 25.25
A0.25 0.25 0 0 1 2.25 25L2.75 25A0.25 0.25 0 0 1 3 25.25L3 25.75
A0.25 0.25 0 0 0 3.25 26L3.75 26A0.25 0.25 0 0 1 4 26.25L4 26.75
A0.25 0.25 0 0 0 4.25 27L6.75 27A0.25 0.25 0 0 1 7 27.25L7 27.75
A0.25 0.25 0 0 1 6.75 28L4.25 28A0.25 0.25 0 0 0 4 28.25L4 28.75
A0.25 0.25 0 0 1 3.75 29L3.25 29A0.25 0.25 0 0 0 3 29.25L3 29.75
A0.25 0.25 0 0 0 3.25 30L3.75 30A0.25 0.25 0 0 1 4 30.25L4 33.75
A0.25 0.25 0 0 1 3.75 34L3.25 34A0.25 0.25 0 0 0 3 34.25L3 34.75
A0.25 0.25 0 0 1 2.75 35L2.25 35A0.25 0.25 0 0 0 2 35.25L2 35.75
A0.25 0.25 0 0 1 1.75 36L0.25 36A0.25 0.25 0 0 0 0 36.25L0 37.75
A0.25 0.25 0 0 0 0.25 38L0.75 38A0.25 0.25 0 0 1 1 38.25L1 39.75
A0.25 0.25 0 0 1 0.75 40L0.25 40A0.25 0.25 0 0 0 0 40.25L0 40.75
A0.25 0.25 0 0 0 0.25 41L2.75 41A0.25 0.25 0 0 0 3 40.75L3 40.25
A0.25 0.25 0 0 1 3.25 40L3.75 40A0.25 0.25 0 0 0 4 39.75L4 39.25
A0.25 0.25 0 0 0 3.75 39L2.25 39A0.25 0.25 0 0 1 2 38.75L2 38.25
A0.25 0.25 0 0 1 2.25 38L2.75 38A0.25 0.25 0 0 0 3 37.75L3 37.25
A0.25 0.25 0 0 1 3.25 37L3.75 37A0.25 0.25 0 0 1 4 37.25L4 37.75
A0.25 0.25 0 0 0 4.25 38L4.75 38A0.25 0.25 0 0 1 5 38.25L5 38.75
A0.25 0.25 0 0 0 5.25 39L6.75 39A0.25 0.25 0 0 1 7 39.25L7 39.75
A0.25 0.25 0 0 1 6.75 40L6.25 40A0.25 0.25 0 0 0 6 40.25L6 40.75
A0.25 0.25 0 0 0 6.25 41L7.75 41A0.25 0.25 0 0 1 8 41.25L8 41.75
A0.25 0.25 0 0 0 8.25 42L9.75 42A0.25 0.25 0 0 0 10 41.75L10 41.25
A0.25 0.25 0 0 1 10.25 41L11.75 41A0.25 0.25 0 0 0 12 40.75L12 39.25
A0.25 0.25 0 0 0 11.75 39L10.25 39A0.25 0.25 0 0 0 10 39.25L10 40.75
A0.25 0.25 0 0 1 9.75 41L9.25 41A0.25 0.25 0 0 1 9 40.75L9 39.25
A0.25 0.25 0 0 0 8.75 39L8.25 39A0.25 0.25 0 0 1 8 38.75L8 38.25
A0.25 0.25 0 0 1 8.25 38L9.75 38A0.25 0.25 0 0 0 10 37.75L10 36.25
A0.25 0.25 0 0 1 10.25 36L10.75 36A0.25 0.25 0 0 0 11 35.75L11 35.25
A0.25 0.25 0 0 0 10.75 35L10.25 35A0.25 0.25 0 0 0 10 35.25L10 35.75
A0.25 0.25 0 0 1 9.75 36L6.25 36A0.25 0.25 0 0 1 6 35.75L6 35.25
A0.25 0.25 0 0 1 6.25 35L7.75 35A0.25 0.25 0 0 0 8 34.75L8 34.25
A0.25 0.25 0 0 0 7.75 34L6.25 34A0.25 0.25 0 0 1 6 33.75L6 33.25
A0.25 0.25 0 0 1 6.25 33L6.75 33A0.25 0.25 0 0 0 7 32.75L7 32.25
A0.25 0.25 0 0 0 6.75 32L6.25 32A0.25 0.25 0 0 1 6 31.75L6 31.25
A0.25 0.25 0 0 1 6.25 31L7.75 31A0.25 0.25 0 0 0 8 30.75L8 30.25
A0.25 0.25 0 0 1 8.25 30L9.75 30A0.25 0.25 0 0 1 10 30.25L10 30.75
A0.25 0.25 0 0 1 9.75 31L9.25 31A0.25 0.25 0 0 0 9 31.25L9 31.75
A0.25 0.25 0 0 0 9.25 32L10.75 32A0.25 0.25 0 0 1 11 32.25L11 32.75
A0.25 0.25 0 0 1 10.75 33L9.25 33A0.25 0.25 0 0 0 9 33.25L9 33.75
A0.25 0.25 0 0 0 9.25 34L10.75 34A0.25 0.25 0 0 0 11 33.75L11 33.25
A0.25 0.25 0 0 1 11.25 33L11.75 33A0.25 0.25 0 0 0 12 32.75L12 32.25
A0.25 0.25 0 0 1 12.25 32L13.75 32A0.25 0.25 0 0 1 14 32.25L14 33.75
A0.25 0.25 0 0 1 13.75 34L12.25 34A0.25 0.25 0 0 0 12 34.25L12 34.75

  at vendor/bacon/bacon-qr-code/src/Renderer/Image/ImagickImageBackEnd.php:168
    164▕         if (null === $this->draw) {
    165▕             throw new RuntimeException('No image has been started');
    166▕         }
    167▕
  ➜ 168▕         $this->image->drawImage($this->draw);
    169▕         $blob = $this->image->getImageBlob();
    170▕         $this->draw->clear();
    171▕         $this->image->clear();
    172▕         $this->draw = null;

      +4 vendor frames
  5   app/Jobs/GenerateQrJob.php:33
      SimpleSoftwareIO\QrCode\Generator::generate()

      +25 vendor frames
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by chapus** [comment]
Im getting a similiar error.
`ERROR: ImagickException: too many bezier coordinates `M10 0.25L10 1.75A0.25 0.25 0 0 0 10.25 2L10.75 2A0.25 0.25 0 0 0 11 1.75...`

**Comment by SimplyCorey** [comment]
Can't reproduce.

**Comment by chapus** [comment]
I just solved. when the URL is too long and using round() was throwing that error.  I removed round() and set errorCorrection.

```
QrCode::format('png')
                    ->size(300)
                    // ->style('round')
                    ->eyeColor(0, 3, 64, 121, 240, 125, 0)
                    ->errorCorrection('M')
                    ->generate(LONG URL);
```
