### ISSUE TITLE
how can I set multiple header in response for this QRCode

### ISSUE THREAD

**Issue by limkuncui** [SimpleSoftwareIO/simple-qrcode#254]
how can I set multiple header in response for this QRCode
``
$svg_img = QrCode::format('svg')->size(100)->margin(5)->backgroundColor(255,55,0)->generate('Hello World!');
return response($svg_img)->header('Content-type','image/svg');
``
how can I add file name into header?
``
header("Content-Disposition: attachment; filename=QRCode.svg");
``

**Comment by SimplyCorey** [comment]
This should be what you need.

https://laravel.com/docs/9.x/responses#file-downloads
