### ISSUE TITLE
Attach QR code to Dompdf generated document

### ISSUE THREAD

**Issue by vint2000** [SimpleSoftwareIO/simple-qrcode#26]
Please Help,
I am just getting an error in the PDF : Image not readable or empty
{!!$message->embedData(QrCode::format('png')->generate('Embed me into an e-mail!'), 'QrCode.png', 'image/png')!!}
Thanks

**Comment by Hesesses** [comment]
How did you solve this?

**Comment by SimplyCorey** [comment]
Does #21 help you?

**Comment by jazeb786** [comment]
I cant send QR code in gmail or yahoo plz guide me 
this is my controller 
foreach ($tickets as $key => $ticket) {
            $ticket['sold'] = $ticketQuantities[$key];
            $ticket['total_paid'] = $ticket->price * $ticketQuantities[$key];
            $ticket->save();
            $ticket->users()->attach($user);
        }
        $user  = User::findOrFail(Auth::user()->id);
        $qrCode=QrCode::generate($ticket->id);
        env("APP_URL");
        Mail::to($user->email)->send(new bookingMail($ticket,$user,$qrCode));
        Session::flash('success', 'You have successfully booked this event and send mail to booking details');
        return view('attendee.eventbookingdetail',compact('ticket' ,'qrCode'));
and this is my email template

 <img src="{!!$message->embedData(QrCode::format('png')->generate($ticket->id), 'QrCode.png', 'image/png')!!}" width="500px" height="200px">

**Comment by SimplyCorey** [comment]
You will likely need to save the QrCode locally and attack it the email using this https://laravel.com/docs/5.5/mail#inline-attachments
