### ISSUE TITLE
problems with umlauts in VCARDS

### ISSUE THREAD

**Issue by Cluster2a** [SimpleSoftwareIO/simple-qrcode#260]
Hey, if I am using an umlaut within a vcard and generating the QRcode :

```
BEGIN:VCARD
VERSION:4.0
PRODID:-//Sabre//Sabre VObject 4.5.0//EN
UID:sabre-vobject-e48beda0-3a29-448d-a253-ef110e528ea6
N:Doe;John;;;
NICKNAME:
ORG:;
ADR;TYPE=WORK:;Bachstraße 1;PLZ;City;;;
NOTE:
END:VCARD
```

```php
QrCode::encoding('UTF-8')->generate($vCard);
```

The following QRcode is generated:
![image](https://user-images.githubusercontent.com/84905165/193477044-6f611832-4221-4161-8c89-ec4091c6a742.png)

Checking this QRcode with https://zxing.org/w/decode, the QRcode seems to be alright:
![image](https://user-images.githubusercontent.com/84905165/193477202-4923e1f2-0e8c-47d2-96f8-d6d30ee4415c.png)

But reading on an android phone will result in an error, and an iPhone will mess up the umlaut:
![image](https://user-images.githubusercontent.com/84905165/193477286-e240032a-f679-4cb7-be69-d00a28e3deac.png)

Is there any way around this? I am not quite sure where the mistake happens.

**Comment by alanpilloud** [comment]
@Cluster2a Hello,

I have exactly the same issue. Do you by any chance remember how you solved it ?

Thanks !

**Comment by alanpilloud** [comment]
I solved it. I simply used vcard v3 instead of v4.
