### ISSUE TITLE
Resolution/quality, different between versions

### ISSUE THREAD

**Issue by tiagocaus** [SimpleSoftwareIO/simple-qrcode#263]
Used version 2 and the qrcode had a good resolution. Now that I migrated to version 4, because I'm using php 8.1, the same qrcode is blurred.

Code used in both versions:
`<img src="data:image/png;base64, '.base64_encode($qrcode->format('png')->size(90)->margin(1)->generate($row['codigo'])).' ">`

# qrcode generated in version 2
> https://i.imgur.com/8xw1BEM.png

# qrcode generated in version 4
> https://i.imgur.com/LCkKPHN.png

Did you notice that in version 4 the edges are a little blurred? They should be clear.

How to solve it?

Thanks.

**Comment by Ander07** [comment]
I had a similar case, and what I did was increase the 'size', while increasing the 'size' improved the definition.
Regards

**Comment by JshGrn** [comment]
Not really sure why this is completed, the generated QR codes are blurry, the only 'workaround' is making them much larger then scaling them down which is really bad solution.
