### ISSUE TITLE
Unable to find custom QR "clickable" method in the documentation

### ISSUE THREAD

**Issue by Benoit1980** [SimpleSoftwareIO/simple-qrcode#264]
Hello,

I am unable to find something like this in your documenation:
```
                    {!! QrCode::size(200)->link([
                    'https://' => 'website.com',
                    'param1' => $user->id,
                    'param2' => $user->email,
                    'param3' => $user->name,
                    ]) !!}
```

Which would then open a website with the below GET parameters upon scanning:
```
https://website.com?id&email@gmail.com&freddy
```

Is this not possible with your library?

As I can see helpers, but nothing in between apart from a single generate() method for a string.

Thank you!

**Comment by SimplyCorey** [comment]
Not sure what you are looking for.  That will just add get parameters.
