### ISSUE TITLE
wifi qr code genrate not working

### ISSUE THREAD

**Issue by majedqatousa** [SimpleSoftwareIO/simple-qrcode#265]
hello  ,  
im trying to genarate new QR Code and save it to my assets , im using this code : 
`\QrCode::size(300)->generate(
        'wifi:WEP/WPA;SSID;PSK;Hidden(True/False)',
        public_path('uploads/user_'.auth()->user()->resturant->id.'_wifi_'.'.svg')
    );`

and its genart Qr Code for text  not wifi 
where is the problem ?

**Comment by SimplyCorey** [comment]
I'd suggest using the build in wifi generator. 

```
QrCode::wiFi([
    'encryption' => 'WPA/WEP',
    'ssid' => 'SSID of the network',
    'password' => 'Password of the network',
    'hidden' => 'Whether the network is a hidden SSID or not.'
]);

```
