### ISSUE TITLE
non-conforming drawing primitive definition

### ISSUE THREAD

**Issue by versantweb** [SimpleSoftwareIO/simple-qrcode#267]
Hello,

When we want to generate a PNG QR Code, we're facing this issue : 

"non-conforming drawing primitive definition `20' @ error/draw.c/DrawImage/3192"

You can find a debug printscreen : [https://beta.easy-aide.ch/images/error.png](https://beta.easy-aide.ch/images/error.png)

And here's the link to see it : https://beta.easy-aide.ch/public/pdf/certificat/28653/html

Any idea ?

Thanks a lot in advance

**Comment by BusinessClick** [comment]
I have the same error with ImageMagick updated just now.

`non-conforming drawing primitive definition '9' @ error/draw.c/RenderMVGContent/4301 `

How did you solved?
Thanks!

**Comment by victorcesae** [comment]
> I have the same error with ImageMagick updated just now.
> 
> `non-conforming drawing primitive definition '9' @ error/draw.c/RenderMVGContent/4301 `
> 
> How did you solved? Thanks!

This is the solution:
https://github.com/Bacon/BaconQrCode/pull/84#issuecomment-991059918
