### ISSUE TITLE
Imagick PHP Extension not loading

### ISSUE THREAD

**Issue by atrivisano** [SimpleSoftwareIO/simple-qrcode#269]
I use barebones for development which consists of:
- Laravel
- PostgreSQL
- PHP

I have followed everything SimpleSoftwareIO provides and everything Imagick provides. There is no solution to this issue thus far.

To start the laravel project I use `php artisan serve` which gives this error below.
![image](https://user-images.githubusercontent.com/5932231/212162882-1a51e98c-fde3-4f36-b90e-6a56b24c15f1.png)

**Comment by SimplyCorey** [comment]
You need to install imagick.
