### ISSUE TITLE
Error generating qr code

### ISSUE THREAD

**Issue by gerciljunio** [SimpleSoftwareIO/simple-qrcode#27]
I have a problem while building the qr code, the error is "max (): Array must contain at least one element" I'm on a ubuntu server (laravel forge) with php 5.6.14 and laravel 5.1, is there any requirement besides the GD or something? thanks!

**Comment by SimplyCorey** [comment]
Please provide the code you are using to generate a QrCode.  Thanks!

**Comment by gerciljunio** [comment]
Sorry!

<img src="data:image/png;base64, {{ base64_encode(QrCode::encoding('UTF-8')->format('png')->margin(1)->size(220)->generate('0023|m123|project|menu')) }}">

**Comment by gerciljunio** [comment]
Sorry!

```
<img src="data:image/png;base64, {{ base64_encode(QrCode::encoding('UTF-8')->format('png')->margin(1)->size(220)->generate('0023|m123|project|menu')) }}">
```

**Comment by SimplyCorey** [comment]
GD is the only requirement.  I ran the code that you provided and it generated the following:

![download](https://cloud.githubusercontent.com/assets/624784/11858569/cdf88430-a430-11e5-8cc6-9e7dedc08733.png)

I am not really sure what is causing your issue.  Can you provide the your routes/controller/view files for me to take a look at?

Thank you

**Comment by yaofong** [comment]
Hi, I have this same error:

ErrorException in line 0:
max(): Array must contain at least one element

I'm running on ubuntu nginx+hhvm laravel 5.1

I can't figure out what's going wrong, can anyone advice?

**Comment by SimplyCorey** [comment]
@yaofong,  please provide the code you are using to create a qrcode.  Thanks!

**Comment by yaofong** [comment]
I'm just using the code from example:
{!! QrCode::generate('Make me into a QrCode!'); !!}

It's running alright on my localhost's apache php5

but show error on hhvm nginx on my live server

**Comment by SimplyCorey** [comment]
I'll have to boot up a hhvm server with nginx installed.  Can you try running the same code but using the size method and let me know if the error still occurs?

{!! QrCode::size(200)->generate('test'); !!}

**Comment by yaofong** [comment]
It's showing the same error

**Comment by SimplyCorey** [comment]
I'll see if I can reproduce this error.  I think it has something to do with hhvm.

**Comment by SimplyCorey** [comment]
@yaofong I have identified the bug that is causing this issue.  It only occurs on HHVM and with version 1 QrCodes.  Longer QrCode will not have this issue.  A pull request has been pushed up stream to fix the bug.  Thank you for reporting

**Comment by yaofong** [comment]
Thanks @SimplyCorey for the fix!

When can we get the new update?

**Comment by SimplyThomas** [comment]
@yaofong, we are working with BaconQrCode on the issue and the update is on their end.

You can check out the pull request and follow the status of our requested fix at https://github.com/Bacon/BaconQrCode/pull/17

**Comment by SimplyCorey** [comment]
@yaofong The bug fix was just merged.  Running composer update at this time should resolve the issue :wink:

**Comment by exskuller** [comment]
i have error : file_get_contents(http://localhost:8000/assets/img/logo_2_0_white.png): failed to open stream: HTTP request failed! (View: /Applications/XAMPP/xamppfiles/htdocs/bo/resources/views/merchant/index.blade.php)
my code:
<img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge(url('assets/img/logo_2_0_white.png'), 0.3, true)
->size(500)->errorCorrection('H')
->generate('Welcome to kerneldev.com!')) !!} ">

can u help me, please

**Comment by exskuller** [comment]
<img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge(url('assets/img/logo_2_0_white.png'), 0.3, true)
->size(500)->errorCorrection('H')
->generate('Welcome to kerneldev.com!')) !!} ">
