### ISSUE TITLE
Class "BaconQrCode\Encoder\Encoder" not found

### ISSUE THREAD

**Issue by adilabbass** [SimpleSoftwareIO/simple-qrcode#272]
I am using SimpleSoftwareIO/simple-qrcode in Laravel 8 application. 

Provider is loaded successfully. 
![image](https://user-images.githubusercontent.com/33801645/216971767-4366860d-2666-45ce-bbc6-b6f24bc281ee.png)

aliases is also added. 
![image](https://user-images.githubusercontent.com/33801645/216971878-c5003f27-c266-4fea-af7e-a2c7ccdc93e2.png)

I am loading the QR code in the blade file which is working fine in the local development server. 

When I load that in production which uses Nginx and Docker. I am getting the below error. 

![image](https://user-images.githubusercontent.com/33801645/216972160-48fcf466-69b9-44da-988a-f81640c1ac55.png)

Can someone assist in this issue.

**Comment by SimplyCorey** [comment]
Cant reproduce.
