### ISSUE TITLE
can't scan while using dot style

### ISSUE THREAD

**Issue by lux10n** [SimpleSoftwareIO/simple-qrcode#273]
hi there, 
When I use `->style('square')` for my QR code, it works, but as soon as I switch to `->style('dot')`, i can't scan the code anymore.
I am currently using Laravel 8.75, my test device is an iPhone 12, and here's an extract from my composer.json file :
` 
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.75",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "mvdnbrk/laravel-model-expires": "^1.8",
        "simplesoftwareio/simple-qrcode": "~4",
        "spatie/laravel-sitemap": "^5.9"
    },
`

**Comment by 9khaledSayed** [comment]
same issue +1

**Comment by MattiaMarchiorato** [comment]
Try to increase the error correction ;)

**Comment by SimplyCorey** [comment]
Increasing error correction would help.  It's really dependent on the scanners and some struggle to read qrcodes that are not squares and black and white.
