### ISSUE TITLE
Can't put logo on the qrcode when using merge or mergeString png image

### ISSUE THREAD

**Issue by 9khaledSayed** [SimpleSoftwareIO/simple-qrcode#274]
Hello i'm tring to put my logo on the qr code put it give me an error ==>
file_get_contents(/home/jevarxac/beta-plus.jevara.funhttps://beta-plus.jevara.fun/public/assets/media/medical-report/female.png): failed to open stream: No such file or directory (View: /home/jevarxac/beta-plus.jevara.fun/resources/views/medical-report.blade.php)

https://beta-plus.jevara.fun/public/assets/media/medical-report/female.png the package make concatenation with image url and the file path become wrong 

![image](https://user-images.githubusercontent.com/40536997/222924537-1777ad67-5f88-4d04-810c-98c0900262e3.png)

**Comment by MattiaMarchiorato** [comment]
Seems the path is wrong "home/jevarxac/beta-plus.jevara.funhttps://beta-plus.jevara.fun/public/assets/media/medical-report/female.png"

Best

MM

**Comment by SimplyCorey** [comment]
Please check your file path.  It can't find it.

**Comment by 9khaledSayed** [comment]
Thank for your response I will try it

**Comment by nadeem706** [comment]
Hi @9khaledSayed 
Are you able to fix this issue ?
Getting same error.

**Comment by 9khaledSayed** [comment]
Hello thanks for your reply i have fixed the path of the logo but still not working it generate an random charcters like that:-
![image](https://user-images.githubusercontent.com/40536997/234054069-74015f0c-ce88-41f2-a802-f816bb8fc731.png)
`
        $qrCode = QrCode::gradient(28, 181, 224, 0, 8, 81, 'horizontal')
                ->format('png')->merge(asset('beta-logos/small-logo.png'), .3, true)
                ->style('dot', 0.9)
                ->size(95)
                ->eyeColor(0, 28, 181, 224, 0, 8, 81)
                ->eyeColor(1, 28, 181, 224, 0, 8, 81)
                ->eyeColor(2, 28, 181, 224, 0, 8, 81)
                ->generate(route('generate_pdf', $invoice->id));
`
and the path of my photo is this https://beta-plus.jevara.fun/public/beta-logos/small-logo.png

**Comment by nadeem706** [comment]
Hi @9khaledSayed 

I am able to fix it by following code

> base64_encode(QrCode::size(500)->format('png')->merge(https://beta-plus.jevara.fun/public/assets/media/medical-report/female.png, .2,true)->errorCorrection('H')->generate($url))

Hope it helps you..
Thanks,
Nadeem(nadeemshkh706@gmail.com)
