### ISSUE TITLE
Laravel 10 - View - Strange Codes

### ISSUE THREAD

**Issue by mafalda2007** [SimpleSoftwareIO/simple-qrcode#286]
Hi, I'm wanting to display a QR in a view, but when I want to display it in png format, strange codes appear.With svg format it works and without format too.

Laravel 10
PHP 8.1

en my view
{{ QrCode::format('png')->generate('Make me a QrCode!'); }}

output:
![error_qr](https://github.com/SimpleSoftwareIO/simple-qrcode/assets/18195074/3c09062c-719a-4644-aadf-067a9ce426ac)

**Comment by daugaard47** [comment]
@mafalda2007 Same issue. Did you happen to figure out the problem?

**Comment by daugaard47** [comment]
I think I figured it out. 
In my model I have a method like this:
```
    public function getQrCodeAttribute(): string
    {
        return base64_encode(QrCode::size(375)
            ->margin(1)
            ->format('png')
            ->merge('images/media/logos/symbol-logos/2/qr-black.png', 0.15, true)
            ->generate(
                $this->getUrlAttribute(),
            ));
    }
```
Then in my view I do the following:
```
<img src="data:image/png;base64, {!! $foo->getKidQrCodeAttribute() !!}" alt="My QR Code" class="w-full h-full object-cover rounded-lg">
```

Works for me. Hope that helps.

**Comment by SimplyCorey** [comment]
This looks like a base64 encoding issue to me.  Going to close this out as it is covered in the docs.

![CleanShot 2023-08-24 at 09 19 47](https://github.com/SimpleSoftwareIO/simple-qrcode/assets/624784/0503d40f-7ce7-47d2-a3b8-e08aa1a68290)
