### ISSUE TITLE
Imagick extension not working with Laravel 10 and PHP 8.2

### ISSUE THREAD

**Issue by reshmindp** [SimpleSoftwareIO/simple-qrcode#289]
When trying to create QR code using simplesoftwareio/simple-qrcode 4.2 getting the below error. Please fix this support issue.
BaconQrCode\Exception\RuntimeException: You need to install the imagick extension to use this back end in file

**Comment by SimplyCorey** [comment]
You need to install imagick or use svg qrcodes.

**Comment by subdesign** [comment]
Not so easy. Same error on Laravel 9/10, PHP 8.0, 8.1, 8.2 , MacOS 12 , Laravel Valet 4.5.0
simple-qrcode ^4.2

Imagick installed (PHP Monitor) #1:
<img width="351" alt="Screenshot 2023-11-14 at 10 49 01" src="https://github.com/SimpleSoftwareIO/simple-qrcode/assets/691695/6f877062-73e5-4081-87a2-fe043ca5b83d">

#2 php.ini:
<img width="281" alt="Screenshot 2023-11-14 at 10 50 03" src="https://github.com/SimpleSoftwareIO/simple-qrcode/assets/691695/1150d471-d246-4c1a-9a3e-35a812840300">

#3 Tinkerwell test:
<img width="620" alt="Screenshot 2023-11-14 at 10 50 59" src="https://github.com/SimpleSoftwareIO/simple-qrcode/assets/691695/0f8ac2f7-c0b0-46f6-93a5-dc9bd1ea9e8d">

ImageMagickBackEnd.php in bacon-qrcode, drops exception:
```php
    public function __construct(string $imageFormat = 'png', int $compressionQuality = 100)
    {
        if (! class_exists(Imagick::class)) {
            throw new RuntimeException('You need to install the imagick extension to use this back end');
        }
        ...
```
original call:
```php
QrCode::format('png')->size(300)->margin(3)->generate($this->qrcode, $qrcode_image_path);
```

So any idea?

EDIT:
if I directly call the bacon qrcode in the project, it works, creates the png:
```php
    Route::get('qrtest', function(){
        $renderer = new ImageRenderer(
            new RendererStyle(400),
            new ImagickImageBackEnd()
        );
        $writer = new Writer($renderer);
        $writer->writeFile('Hello World!', base_path('qrcode2.png'));
    });
```

**Comment by hihebark** [comment]
Same issue here, same php and laravel version!

**Comment by theterrificm** [comment]
Hi Guys, does anyone of you find any solution? I want to use svg qr codes and don't want to install the imagick ext?
