### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by canfiax** [SimpleSoftwareIO/simple-qrcode#30]
GREAT library! Really good job.

What about caching? I guess you could easily cache the QR Codes sorely by its value?

**Comment by SimplyCorey** [comment]
Hey there.  Thank you for your warm remarks.  There are many options that you could choose if you want to cache.  The easiest one would be just to save the input into the generate method and check if a qrcode has already been generated for this output.

**Comment by canfiax** [comment]
Thanks, but what about natively supporting this in the package? I.e. using Laravels native cache system etc; so that you do not have to implement your own :)

**Comment by SimplyCorey** [comment]
@canifax. Caching would be outside the scope of this library.  Sorry.  We like to keep our libraries focused in a single task.
