### ISSUE TITLE
should go for bacon/bacon-qr-code ^3.0 

### ISSUE THREAD

**Issue by bvicini** [SimpleSoftwareIO/simple-qrcode#304]
using other plugins, like filament 3 breezy that require bacon/bacon-qr-code ^3.0 the installation gives error due to version mismatching

**Comment by bvicini** [comment]
I see a pull request just for that

**Comment by bvicini** [comment]
It seems that a pull request for upgrading to bacon/bacon-qr-code ^3.0 has been accepted, but trying installation still gives version conflict because of version 2

**Comment by rossbearman** [comment]
The pull request hasn't been accepted yet, but you can [change your composer.json to pull in the PR branch](https://github.com/SimpleSoftwareIO/simple-qrcode/pull/303#issuecomment-2180897967) instead to fix it in the short term.

**Comment by bvicini** [comment]
ty for your answer
