### ISSUE TITLE
Class 'SimpleSoftwareIO\QrCode\QrCodeServiceProvider::class' not found

### ISSUE THREAD

**Issue by vincent03460** [SimpleSoftwareIO/simple-qrcode#32]
tried and followed every steps from here
https://github.com/SimpleSoftwareIO/simple-qrcode
but I still get this error

> **FatalErrorException in ProviderRepository.php line 150:
> Class 'SimpleSoftwareIO\QrCode\QrCodeServiceProvider::class' not found**

Using laravel 5.0...any idea? tried
-composer update
-composer self-update
-composer dump-autoload
-composer update -o

added this in composer.json,autoload there
```
"psr-0": {
	"SimpleSoftwareIO\\QrCode\\": "src"
}
```

but nothing work, please help me. Did I miss anything else?

**Comment by SimplyCorey** [comment]
Are you seeing this error inside of the command prompt?

**Comment by vincent03460** [comment]
nope, in the webpage...removed the ::class...no more error, but this code QrCode stated undifined class in blade side.

`<div class="visible-print text-center">
    {!! QrCode::size(100)->generate(Request::url()); !!}
    <p>Scan me to return to the original page.</p>
{{$qr}}
</div>`

this in controller,and used it in blade,nth comes out.
`$qr = QrCode::size(200)->generate('http://laravelacademy.org');`
Command prompt everything works fine.

**Comment by SimplyCorey** [comment]
Somethings like something is not configured correctly.  Can I see your `config/app.php` file and `composer.json` file please?

**Comment by vincent03460** [comment]
I think so. Sure, here are the setting config/app.php
`
	'providers' => [

		/*
		 * Laravel Framework Service Providers...
		 */
		'Illuminate\Foundation\Providers\ArtisanServiceProvider',
		'Illuminate\Auth\AuthServiceProvider',
		'Illuminate\Bus\BusServiceProvider',
		'Illuminate\Cache\CacheServiceProvider',
		'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
		'Illuminate\Routing\ControllerServiceProvider',
		'Illuminate\Cookie\CookieServiceProvider',
		'Illuminate\Database\DatabaseServiceProvider',
		'Illuminate\Encryption\EncryptionServiceProvider',
		'Illuminate\Filesystem\FilesystemServiceProvider',
		'Illuminate\Foundation\Providers\FoundationServiceProvider',
		'Illuminate\Hashing\HashServiceProvider',
		'Illuminate\Mail\MailServiceProvider',
		'Illuminate\Pagination\PaginationServiceProvider',
		'Illuminate\Pipeline\PipelineServiceProvider',
		'Illuminate\Queue\QueueServiceProvider',
		'Illuminate\Redis\RedisServiceProvider',
		'Illuminate\Auth\Passwords\PasswordResetServiceProvider',
		'Illuminate\Session\SessionServiceProvider',
		'Illuminate\Translation\TranslationServiceProvider',
		'Illuminate\Validation\ValidationServiceProvider',
		'Illuminate\View\ViewServiceProvider',
        'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',
		'Mews\Captcha\CaptchaServiceProvider',
		'SimpleSoftwareIO\QrCode\QrCodeServiceProvider',

		/*
		 * Application Service Providers...
		 */
		'App\Providers\AppServiceProvider',
		'App\Providers\BusServiceProvider',
		'App\Providers\ConfigServiceProvider',
		'App\Providers\EventServiceProvider',
		'App\Providers\RouteServiceProvider',

	],`

`

	'aliases' => [

		'App'           => 'Illuminate\Support\Facades\App',
		'Artisan'       => 'Illuminate\Support\Facades\Artisan',
		'Auth'          => 'Illuminate\Support\Facades\Auth',
		'Blade'         => 'Illuminate\Support\Facades\Blade',
		'Bus'           => 'Illuminate\Support\Facades\Bus',
		'Cache'         => 'Illuminate\Support\Facades\Cache',
		'Config'        => 'Illuminate\Support\Facades\Config',
		'Cookie'        => 'Illuminate\Support\Facades\Cookie',
		'Crypt'         => 'Illuminate\Support\Facades\Crypt',
		'DB'            => 'Illuminate\Support\Facades\DB',
		'Eloquent'      => 'Illuminate\Database\Eloquent\Model',
		'Event'         => 'Illuminate\Support\Facades\Event',
		'File'          => 'Illuminate\Support\Facades\File',
		'Hash'          => 'Illuminate\Support\Facades\Hash',
		'Input'         => 'Illuminate\Support\Facades\Input',
		'Inspiring'     => 'Illuminate\Foundation\Inspiring',
		'Lang'          => 'Illuminate\Support\Facades\Lang',
		'Log'           => 'Illuminate\Support\Facades\Log',
		'Mail'          => 'Illuminate\Support\Facades\Mail',
		'Password'      => 'Illuminate\Support\Facades\Password',
		'Queue'         => 'Illuminate\Support\Facades\Queue',
		'Redirect'      => 'Illuminate\Support\Facades\Redirect',
		'Redis'         => 'Illuminate\Support\Facades\Redis',
		'Request'       => 'Illuminate\Support\Facades\Request',
		'Response'      => 'Illuminate\Support\Facades\Response',
		'Route'         => 'Illuminate\Support\Facades\Route',
		'Schema'        => 'Illuminate\Support\Facades\Schema',
		'Session'       => 'Illuminate\Support\Facades\Session',
		'Storage'       => 'Illuminate\Support\Facades\Storage',
		'URL'           => 'Illuminate\Support\Facades\URL',
		'Validator'     => 'Illuminate\Support\Facades\Validator',
		'View'          => 'Illuminate\Support\Facades\View',
        'Formatter'     => 'App\Libraries\Formatter',
        'Globals'       => 'App\Libraries\Globals',
        'JsValidator'   => 'App\Libraries\JsValidator',
		'QrCode'        => 'SimpleSoftwareIO\QrCode\Facades\QrCode'
	],`

composer.json
`{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"doctrine/dbal": "~2.3",
		"barryvdh/laravel-ide-helper": "v2.0.3",
		"webpatser/laravel-countries": "1.4.3",
		"mews/captcha": "~2.0",
		"simplesoftwareio/simple-qrcode": "1.3.*"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		},
		"psr-0": {
			"SimpleSoftwareIO\\QrCode\\": "src"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
`

**Comment by vincent03460** [comment]
I think so.  There you go. Thanks
[files.zip](https://github.com/SimpleSoftwareIO/simple-qrcode/files/124130/files.zip)

**Comment by vincent03460** [comment]
[files.zip](https://github.com/SimpleSoftwareIO/simple-qrcode/files/124135/files.zip)
I think so. There you go. Thanks

**Comment by vincent03460** [comment]
Tried over hundred of times...this works for me but not image file, unable to save/download
```
use SimpleSoftwareIO\QrCode\BaconQrCodeGenerator;

$qrcode = new BaconQrCodeGenerator;
$qrcode->size(500)->generate('Make a qrcode without Laravel!');
```

Tried up added a format inside it, but after added, the QRCode becomes alien text
`�PNG  IHDR!!؆U87IDATH��VA�0����d�C5�C���PSGB��!=��n�u7��0^�% ��%w_k�%����o~o��Q%��H@OUbH�WdN��!F�{�G�D6�����f%0�Ԣ8xν�iM�?�Cf�Ǉ؜���h�R���]�iM��Q�}���.K�/7��� p�䌁�xI?��U���g�"G��$ �����jz�*!Gwm5�&����!KL�j>�f�V�(s�̦��/����`�dt��LR�IEND�B`�`

any  idea?

**Comment by vincent03460** [comment]
It works now. I removed everything and reupdated again. Thanks a lot!

**Comment by SimplyCorey** [comment]
I was going to recommend that.  Glad everything worked out!  Let us know if you run into anymore issues.
