### ISSUE TITLE
why the png file is so small

### ISSUE THREAD

**Issue by mani95lisa** [SimpleSoftwareIO/simple-qrcode#33]
code:
```
QRCode::size(430)->margin(0)
            ->format('png')
            ->generate(informations', '../public/qrcode/code.png');
```

![code](https://cloud.githubusercontent.com/assets/1968989/13378085/b702c7d6-de32-11e5-9750-40f6daccaefa.png)

when I remove `format('png')` and change file name is `code.svg`, works fine.

**Comment by SimplyCorey** [comment]
Hey there,

Format needs to be the first method called or it will overwrite all of the other set properties.  

Try this

```
QRCode::format('png')
             ->size(430)->margin(0)
            ->generate(informations', '../public/qrcode/code.png');
```

[See `format` method](https://github.com/SimpleSoftwareIO/simple-qrcode#format-change)

**Comment by mani95lisa** [comment]
Thanks!
