### ISSUE TITLE
Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor()

### ISSUE THREAD

**Issue by Liu-xu-dong** [SimpleSoftwareIO/simple-qrcode#36]
I used to in other project used this plugin, but now I'm in a new project in this mistake.What is the meaning of this?

**Comment by SimplyCorey** [comment]
Can you please provide the code that you used?  You shouldn't be getting this error.

**Comment by Liu-xu-dong** [comment]
I'm sorry, I forgot to open the gd, now the problem solved.Thank you！

**Comment by librallaw** [comment]
I get the same error, please what do I do, I have installed php gd on my conputer

**Comment by SimplyCorey** [comment]
@librallaw What does your phpinfo() look like?
