### ISSUE TITLE
Sending qrcode through api

### ISSUE THREAD

**Issue by michaeltansy** [SimpleSoftwareIO/simple-qrcode#37]
Hi I have question regarding using this package. So i tried sending the qrcode xml data. how do I read the data in view page? I tried using <img src="{{data}}"> (i use angularjs) but the tag is not working as what i expected. Any help would be appreciated!!

**Comment by SimplyCorey** [comment]
Are you trying to load a qrcode through an IMG tag?  I'm a little confused on what you are trying to accomplish.

**Comment by hemantachhami19** [comment]
@SimplyCorey  how can i send through the api endpoint . since this package uses xml instead?
