### ISSUE TITLE
[Feature Request] Background Transparency

### ISSUE THREAD

**Issue by rsantosmello** [SimpleSoftwareIO/simple-qrcode#38]
I'm using this package to show QR code on my page, but I need to make the background transparent.

How I can do it?

```
<div >
{!! QrCode::size(300)->color(255,255,255)->backgroundColor(0,0,0)->margin(0)->generate(Request::url()); !!}
</div>
```

**Comment by SimplyCorey** [comment]
Currently, this is not supported.  There is a pull request open upstream that would allow this to happen.  I will check on its status and see if we can get this put into the next release.

**Comment by bryanjamesmiller** [comment]
BaconQrCode now provides an Alpha color class that perhaps could be used to accomplish this:  https://github.com/Bacon/BaconQrCode/blob/2.0.0/src/Renderer/Color/Alpha.php

**Comment by SimplyThomas** [comment]
We have to upgrade to BaconQrCode 2.0.0 to support this.

Tagged this under the 3.0.0 release.

**Comment by SimplyCorey** [comment]
This is resolved in v3 which I am finishing up the docs for and will push up this week.
