### ISSUE TITLE
I'm Chinese Developer ,I can try translation this project document.

### ISSUE THREAD

**Issue by blusewang** [SimpleSoftwareIO/simple-qrcode#40]
But First of all, I need a success trial ^_^

**Comment by SimplyCorey** [comment]
It would be great if you could translate the document :)

**Comment by blusewang** [comment]
I will start translate you project README.md to Chinese, but How do I send result to you?

**Comment by blusewang** [comment]
I have translated 50%!

**Comment by SimplyCorey** [comment]
Awesome, thank you!  Just open a pull request up when you are finished to `docs/zh/readme.md`

**Comment by blusewang** [comment]
OK
