### ISSUE TITLE
Max string length size

### ISSUE THREAD

**Issue by llioor** [SimpleSoftwareIO/simple-qrcode#42]
Hello,
1. What is the maximum length size of a generated string?
2. Do we have relation between "string length" to "size()" function?
3. Do we have relation between "string length" to "errorCorrection('*******Change to Char******')"?

10xxxx, Lior :)

**Comment by llioor** [comment]
is it "Alphanumeric 4,296" from WIKI https://en.wikipedia.org/wiki/QR_code#Error_correction

**Comment by SimplyCorey** [comment]
This would depend on the settings you use when you generate the QrCode.  It is limited by the standard.  This would be version 40 with L error correction.  The encoding would greatly change the amount of characters that can be put within the QrCode.    

The `size` method just sets the height/width of the QrCode in pixels.  It has nothing to do with the length of the encoded string.

**Comment by llioor** [comment]
@SimplyCorey  Thank you very much for the answer... it is more clear right now!
Is there any way to validate if specific string (URL) is OK to be generated.
For example how can I know that:
http://www.google.com will be OK for error correction 'L'?

Thank you...

**Comment by llioor** [comment]
I got an answer here:

https://github.com/Bacon/BaconQrCode/issues/21#issuecomment-221128421

Thank you very much for the help as well!!!
