### ISSUE TITLE
Call to undefined function BaconQrCode\Encoder\iconv()

### ISSUE THREAD

**Issue by f0ntana** [SimpleSoftwareIO/simple-qrcode#43]
i had try composer update, 

when i use this i get the error
```
<div class="visible-print text-center">
                {!! QrCode::size(100)->generate($register->token) !!}
                <p>Scan me to return to the original page.</p>
            </div>
```

**Comment by SimplyCorey** [comment]
You need to ensure you have iconv installed on your system.  Refer to #16 for further information.

Please be afraid to ask if you need anymore help.

**Comment by f0ntana** [comment]
i have this installed

![screen shot 2016-06-15 at 22 57 41](https://cloud.githubusercontent.com/assets/6570783/16104183/f2d45c92-334c-11e6-9c7d-72bfdeb89e54.png)

**Comment by SimplyCorey** [comment]
Please provide your php.ini and phpinfo(); file.

**Comment by f0ntana** [comment]
[phpinfo().pdf](https://github.com/SimpleSoftwareIO/simple-qrcode/files/317617/phpinfo.pdf)
[php.txt](https://github.com/SimpleSoftwareIO/simple-qrcode/files/317620/php.txt)

**Comment by SimplyCorey** [comment]
I am not familiar with Darwin Linux but iconv is not installed correctly for PHP.  `iconv` is a PHP function.

Try running `sudo apt-get install php7-iconv`

**Comment by SimplyThomas** [comment]
@f0ntana it looks as though you're using OSX? As @SimplyCorey said, it looks like you might not have the most updated `iconv` installed. To get the correct version installed depends heavily on how you installed php7 on your system. 

It looks like the most common way to install php7 is through MacPorts. If that's what you used, be sure to try to run the following on your system: `sudo port php70-iconv`

If this doesn't fix your issue, please let us know and we'll continue to help you in any way we can.

**Comment by f0ntana** [comment]
i had an error :

```Error: Unrecognized action "port php70-iconv"```

**Comment by f0ntana** [comment]
no resolve ;/

**Comment by SimplyCorey** [comment]
Does this help?

http://superuser.com/questions/394219/compiling-php-on-os-x-iconv-works-only-if-forced-to-64-bit

**Comment by f0ntana** [comment]
No, i don't know, i will reinstall all, and see whats happends, in my serve
works fine, linux.

Thanks for help.

2016-06-19 9:10 GMT-04:00 Corey McCormick <notifications@github.com>:
