### ISSUE TITLE
QrCode always returns small image regardless "size()" parameter

### ISSUE THREAD

**Issue by vadag** [SimpleSoftwareIO/simple-qrcode#46]
I'm using QrCode from Laravel. And it always 29px * 29px not depenpding of what size I specify. It happens both for PNG and SVG

**Comment by SimplyCorey** [comment]
Please provide the code you are using.

**Comment by SimplyCorey** [comment]
Closing as no response.

**Comment by koolfreak** [comment]
Experienced same issue my code is QrCode::size(250)->format('png')->generate('123456'); always 29x29
Also can i download the qrcode without saving it first? thanks
