### ISSUE TITLE
How to insert a line break?

### ISSUE THREAD

**Issue by johanWP** [SimpleSoftwareIO/simple-qrcode#47]
hi, I've been trying to insert a line break into the info I'm encoding in the QR but I haven't been able to.  I've tried many different things including adding a "\n" char with no results.  Any help?

**Comment by ahmedmaazin** [comment]
I achieved it using newline "\n" 
Can you send more details?

**Comment by SimplyCorey** [comment]
It is really going to depend on the QrCode reader and how it chooses to display the items.
