### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#51]
Looking for a kind soul to translate our documents into Spanish.

Translate: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/en/README.md
Place new file here: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/es/README.md

We will place your name into our thank you section within the change log!

**Comment by simocosimo** [comment]
I don't know Spanish sadly, but I can translate that in Italian if you want

**Comment by SimplyCorey** [comment]
@simocosimo  I would love that.  Opening up some more language tickets now :)

**Comment by SimplyCorey** [comment]
See #52.  Thanks!

**Comment by gtarraga** [comment]
I can translate to spanish

**Comment by SimplyCorey** [comment]
@gtarraga Thanks for the pull request!  I'll merge it in later today

**Comment by SimplyCorey** [comment]
@gtarraga Thanks again.  Pushing this out now.  Fixed in #61
