### ISSUE TITLE
Italian  Translation

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#52]
Looking for a kind soul to translate our documents into Italian.

Translate: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/en/README.md
Place new file here: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/it/README.md

We will place your name into our thank you section within the change log!

**Comment by simocosimo** [comment]
I can do this! 
Starting right now! :)

**Comment by SimplyCorey** [comment]
Fixed in #58.  @simocosimo Thanks!
