### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#53]
Looking for a kind soul to translate our documents into Portuguese.

Translate: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/en/README.md
Place new file here: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/pt/README.md

We will place your name into our thank you section within the change log!

**Comment by felipewmartins** [comment]
Hi @SimplyCorey , I can translate to PT-Br language?

**Comment by SimplyCorey** [comment]
@felipewmartins That will work.  Please put it under https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/pt-br/README.md

Thank you very much!

**Comment by felipewmartins** [comment]
Nice @SimplyCorey !. I will work on it!

**Comment by allexandresampaio** [comment]
If you still need some help in portuguese, tell me!

**Comment by SimplyCorey** [comment]
@allexandresampaio That would be awesome!  Let me know if you have any questions

**Comment by SimplyCorey** [comment]
See #65 

Thanks everyone for your help.
