### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#55]
Looking for a kind soul to translate our documents into Korean.

Translate: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/en/README.md
Place new file here: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/ko/README.md

We will place your name into our thank you section within the change log!

**Comment by SimplyThomas** [comment]
Hacktoberfest has concluded. Cleaning up Issues.
