### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#56]
Looking for a kind soul to translate our documents into Japanese .

Translate: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/en/README.md
Place new file here: https://github.com/SimpleSoftwareIO/simple-qrcode/blob/develop/docs/ja/README.md

We will place your name into our thank you section within the change log!

**Comment by SimplyThomas** [comment]
Hacktoberfest has concluded. Cleaning up Issues.
