### ISSUE TITLE
Can this be used in wechat(weixin) that I can scan and redirect to the URL?

### ISSUE THREAD

**Issue by phoenixg** [SimpleSoftwareIO/simple-qrcode#6]

**Comment by SimplyCorey** [comment]
我很抱歉，我不会说中国话。你可以用英文写你的问题？

Sorry, I do not speak Chinese.  Can you write your question in English?

**Comment by SimplyCorey** [comment]
What do you mean can it be used in WeChat? You could generate the QrCode outside of Laravel using

    $qrcode = new \SimpleSoftwareIO\QrCode\BaconQrCodeGenerator();
    $qrcode->generate('Make a qrcode');

This would work within any PHP app which could then be scanned by any QrCode scanner.

Does that help?

**Comment by SimplyCorey** [comment]
So after a quick read, it appears that a WeChat QrCode is just a URL.  So if you know the parameters of the URL, you should simply be able to pass them in and it will generate a QrCode.

**Comment by phoenixg** [comment]
I will let you know in several days, Thanks.

**Comment by phoenixg** [comment]
It works in Wechat, thank you!

**Comment by SimplyCorey** [comment]
Awesome :smile:

Care to share what you built?

**Comment by phoenixg** [comment]
Actually I just use the default sample code then works.:)
