### ISSUE TITLE
[Feature Request] Fancy QrCodes

### ISSUE THREAD

**Issue by 4val0v** [SimpleSoftwareIO/simple-qrcode#69]
Will patterns support ?
Example [img ](https://imgur.com/a/sRGkP)\- site [Scanova.io](https://app.scanova.io/)
Out qr - **[img](http://imgur.com/a/wh572)**

You can also look on the website: _https://www.unitag.io/qrcode_

**Comment by SimplyCorey** [comment]
@4val0v We have plans to bring in this feature.  Currently there is no time frame though.  If you get ambitious, feel free to make a pull request.

**Comment by DASPRiD** [comment]
This is now a supported feature in the upstream QR code renderer.

**Comment by SimplyCorey** [comment]
This is resolved in v3 which I am finishing up the docs for and will push up this week.

![image](https://user-images.githubusercontent.com/624784/82928094-ba985680-9f4f-11ea-9643-a8498cd6e10f.png)
