### ISSUE TITLE
laravel 5 Call to undefined method SimpleSoftwareIO\QrCode\BaconQrCodeGenerator::handle()

### ISSUE THREAD

**Issue by kaaboeld** [SimpleSoftwareIO/simple-qrcode#7]
Follow all the steps in app.php

In my Controller added (without instructions) in __construct(): 
$this->middleware('qrcode');

in my view:
```
{{ QrCode::generate('Make me into a QrCode!'); }}
```

and i have error in log:

> FatalErrorException in Pipeline.php line 125:
> Call to undefined method SimpleSoftwareIO\QrCode\BaconQrCodeGenerator::handle()

**Comment by SimplyCorey** [comment]
We will be updating this package in the next few days to work with Laravel 5.

**Comment by kaaboeld** [comment]
Thanks, I'll wait

**Comment by dragonfire1119** [comment]
Have you gotten time to update this package yet for Laravel 5?

**Comment by SimplyCorey** [comment]
Yes.  Ill push the release tomorrow.  Been away from home for a few days, sorry.

**Comment by SimplyCorey** [comment]
@kaaboeld This has been released as of today.  Very sorry for the long wait!  Life has been very busy lately.

You should not have to use $this->middleware('qrcode') to use this package.  Just place QrCode::generate('QrCode'); within a view or route and it will work. :smile: Enjoy!
