### ISSUE TITLE
[BUG] Generating qr codes in a loop leads  to empty qr codes

### ISSUE THREAD

**Issue by brizov43** [SimpleSoftwareIO/simple-qrcode#70]
When using the QrCode facade in a foreach loop, the qr codes get saved to storage and appear empty. I've tested a custom loop with the BaconQr code, assigning the $renderer anew in every loop and it works. This means the QrCode should become a factory as to accomodate looping creation.
For example, this doesn't work:
`foreach ($iterator as $iter) {
  QrCode::generate('something'.$iter, '../path/something'.$iter.'.svg');
}`
This works fine:
`foreach ($iterator as $iter) {
  $renderer = new Svg();
  $writer = new Writer($renderer); 
  $writer->writeFile('something'.$iter, '../public/something'.$iter.'.svg');
}`

**Comment by SimplyCorey** [comment]
@brizov43 Fixed in 1.5.1

**Comment by brizov43** [comment]
Great job! Thanks.
