### ISSUE TITLE
QR code can't be scan after merged

### ISSUE THREAD

**Issue by kavierkoo** [SimpleSoftwareIO/simple-qrcode#73]
It seems to be the QR code was not able to be scan after merged with logo using code below:
` <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge('\public\img\logo.png')->size(500)->generate('Test!')) !!} ">`

It works fine before merging it but it will not work after merge.

**Comment by SimplyCorey** [comment]
What is your error level set to?

**Comment by kavierkoo** [comment]
Oh.. I'm terribly sorry about the wrong issue, after i allocate it to High it works. Really sorry for any inconveniences caused.

**Comment by SimplyCorey** [comment]
👍
