### ISSUE TITLE
QR code unable to scan

### ISSUE THREAD

**Issue by kavierkoo** [SimpleSoftwareIO/simple-qrcode#74]
The code to call 
` <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->merge('\public\img\logo.png')->errorCorrection('H')->size(500)->generate($qrcontent)) !!} ">`

Content in $qrcontent: `2016-12-21-DBDS-UC2F1501IT(ISS),UC2F1501IT(FC),UCD2F1309DIT-lecturer`

Sorry for disturbing again, I really have no idea how to fix it

**Comment by SimplyCorey** [comment]
The scanabity really depends on the Qrcodes reader.  One thing you could try is to reduce the percentage of the logo placed on top of the Qrcodes by using the second parameter.   

Merge(logo, 15)

**Comment by SimplyCorey** [comment]
Also, if you want to provide me with the image you are using. I can see if something funny is going on.

**Comment by kavierkoo** [comment]
[Default size](https://drive.google.com/open?id=0BySNOzogzCU5RmRXZnV3bGV0MFU)
[.15 Size](https://drive.google.com/open?id=0BySNOzogzCU5ODBzM1ctSkRFVFE)

**Comment by SimplyCorey** [comment]
@kavierkoo Which scanner app are you using?

**Comment by kavierkoo** [comment]
iPhone app named QR Reader, anyway I requirement changed and I manage to achieve what I wanted to by changing the content to read a generated ID from database instead, thanks for the assisting
