### ISSUE TITLE
imagecreatefromstring(): Data is not in a recognized format

### ISSUE THREAD

**Issue by vranvs** [SimpleSoftwareIO/simple-qrcode#77]
Try to use the merge function with your library to add a logo to the center of my QR code.

My file is in .png format.

my code:
`$qrcode = QrCode::size(400)->
  merge('\public\img\covalent_qr.png', 0.3)->
  errorCorrection('H')->
  generate('lol');
  return $qrcode;`

The error I'm getting (also in title):

> ErrorException in Image.php line 21: imagecreatefromstring(): Data is not in a recognized format

Thanks

**Comment by SimplyCorey** [comment]
You have to use the png format. Try this:

`$qrcode = QrCode::format('png')->size(400)-> merge('\public\img\covalent_qr.png', 0.3)-> errorCorrection('H')-> generate('lol'); return $qrcode;`

**Comment by luanrodrigues** [comment]
same here. :/

**Comment by SimplyCorey** [comment]
Did you use the png format?

**Comment by luanrodrigues** [comment]
Yes, I did @SimplyCorey

**Comment by luanrodrigues** [comment]
this is the erro i got: http://i.imgur.com/KY6NoZ6.png

**Comment by SimplyCorey** [comment]
That's not an error.  Thats the PNG image.  You need to wrap it.

`<img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(100)->generate('Make me into an QrCode!')) !!} ">`

**Comment by ahmedbondok2006** [comment]
ErrorException
imagecreatefromstring(): Data is not in a recognized format
  i have this error when making this code

public function imageQrCode()
    {
        $image = QrCode::format('png')
            ->merge(public_path('website/images/barcode.png'), 0.5, true)
            ->size(500)
            ->generate('A simple example of QR code!');
        return response($image)->header('Content-type','image/png');

    }

**Comment by ahmedbondok2006** [comment]
i need to send qr code within email
