### ISSUE TITLE
Problem to install on Laravel 5.4

### ISSUE THREAD

**Issue by silasrm** [SimpleSoftwareIO/simple-qrcode#79]
Hi,

I'm trying to install on 5.4 but composer says:

  Problem 1
    - The requested package simplesoftwareio/simple-qrcod could not be found in any version, there may be a typo in the package name.

Any solution?

**Comment by SimplyCorey** [comment]
`simplesoftwareio/simple-qrcod` should be `simplesoftwareio/simple-qrcode`

**Comment by silasrm** [comment]
Hi @SimplyCorey,

Sorry!

Thks
