### ISSUE TITLE
How to use helper?

### ISSUE THREAD

**Issue by salttechno** [SimpleSoftwareIO/simple-qrcode#9]
Hello, I'm not able to use 
QrCode::email('foo@bar.com', 'This is the subject.', 'This is the message body.');

It throws following error :
Call to undefined method SimpleSoftwareIO\QrCode\BaconQrCodeGenerator::email()

**Comment by SimplyCorey** [comment]
This hasn't been released yet.  You are reading the docs for the Dev version.  I will release it tomorrow and it should work correctly.

**Comment by salttechno** [comment]
Great! Thanks for quick response.


Regards,
Nilesh G

**Comment by SimplyCorey** [comment]
This has been released in 1.2 as of today.  Enjoy!
