### ISSUE TITLE
Why does the bitcoin qr code have a fat white border around it ?

### ISSUE THREAD

**Issue by htonkovac** [SimpleSoftwareIO/simple-qrcode#90]
Please tell me how to make this fat ugly border smaller, thank you

**Comment by SimplyCorey** [comment]
What does your code look like.

**Comment by htonkovac** [comment]
{!!QrCode::size(250)->BTC('$public_key', $btc->price)!!}

The svg generated has the QR code, but also a fat white border. 

Also is there a way to increase the level of error correction?

**Comment by htonkovac** [comment]
It is 36 "rectangles" wide

**Comment by SimplyCorey** [comment]
It's all in the docs.  Change margin and errorCorrection to what you desire.
