### ISSUE TITLE
How i save QR code into database and retrieve it?

### ISSUE THREAD

**Issue by chonchol** [SimpleSoftwareIO/simple-qrcode#91]
There is no step by step documentation how i save qr code into database and retrieve it. I have tried below way: 

Controller for store QR code into database:

    public function store(Request $request)
    {
        //
        ini_set('max_execution_time', 180);
        $limit = $request->get('qrcode_quantity');
        for ($i=1; $i <= $limit ; $i++) { 
            # code...
            $qrcode = new Qrcode();
            $qrcode->user_id = Auth::user()->id;
            //$qrcode->user_id = 1;
            $corres_connection = str_random(7);
            $qrcode->correspond_code = $corres_connection;
            $qrcode->qrcode_note = $request->get('qrcode_note');
            $qrcode->save();
        }
        $request->session()->flash('alert-success', 'QR code Successfully Created!');
        return Redirect::to('admin/qrcode/create');
    }

And blade to viewing it without save it:

         @foreach($qrcodes as $qrcode)
                <tr>
                    <td> <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(100)->generate($redirectedPage.$qrcode->id)) !!} "> </td>
                    <td> <a href="data:image/png;base64, {!! base64_encode(QrCode::format('png')->size(100)->generate($redirectedPage.$qrcode->id)) !!} " class="btn btn-primary" download>{{ trans('common.download_button') }}</a> </td>
                 </tr>                            
          @endforeach

It will retrieve all `id` as a QR code. Its take huge time because i have more that 5k QR code into my table. It takes huge time because i didn't save it into any folder. 

Now my question is how can create QR code and save into database (folder also) so that when i retrieve it then it takes less time?  Please give me an solution. I am very worry about this. Thanks in advance.

**Comment by SimplyCorey** [comment]
This isn't really anything to do with the library, but is your own implementation details.  As stated in #85, you can pre-create the files and save them using the second argument in the generate method to save them to a file.  From there, you can do what you want with them.  You can put them in S3, save them as binary data in a database, its up to you.  Although, I don't really recommend saving images to a database.  You could also try not making 5,000 qrcodes at a time and paginate them.

`QrCode::generate('your qrcode', 'yourfilename.svg')` <-- Save this where ever you want.

**Comment by chonchol** [comment]
How i insert image path into database? `../public/qrcodes/yourfilename.svg` i want to save when creating any qrcodes. Please tell me how i save the image path into database.

**Comment by SimplyCorey** [comment]
I suggest you read up on SQL and Laravel Eloquent if you are struggling with this.

**Comment by pitss-official** [comment]
@chonchol you can convert image into base 64 string and then store in database
for retrieving the image back in the front end, you have to again convert that string into img
