### ISSUE TITLE
Pass encoding as a parameter

### ISSUE THREAD

**Issue by hamzstramgram** [SimpleSoftwareIO/simple-qrcode#98]
By default the encoding is set to ISO-8859-1 in the Bacon library.

So when trying to generate a QR code with muti-bytes characters (like chinese name when generating a vCard) I get an error "Could not encode content to ISO-8859-1". Apparently it is possible to pass the encoding as third parameter to the writeFile() method in BaconQrCode.

Is it possible to add this as a parameter or settings somewhere?

**Comment by emilas44** [comment]
Yes you can change the encoding, for example:

`        $qrCode = QrCode::format($qrImg)
            ->encoding('UTF-8')
            ->margin(10)
            ->size(630)
            ->generate($vcard, public_path("/qr/" . $folderName ."/". $fileName . ".". $qrImg))`

**Comment by SimplyCorey** [comment]
This can already be done using @emilas44 method
