### ISSUE TITLE
I have the white square

### ISSUE THREAD

**Issue by goszowski** [SimpleSoftwareIO/simple-qrcode#99]
<img width="369" alt="qr-code-error" src="https://user-images.githubusercontent.com/10208931/36852812-6fbb8b4a-1d75-11e8-9ba8-81890b937509.png">
<img width="336" alt="qr-code-error-2" src="https://user-images.githubusercontent.com/10208931/36852823-76acc400-1d75-11e8-886a-cfe12ace4980.png">
<img width="574" alt="qr-code-error-3" src="https://user-images.githubusercontent.com/10208931/36852880-9bf27bba-1d75-11e8-8b01-289fa97c9b2d.png">

**Comment by SimplyCorey** [comment]
Does this only occur with the svg?  Have you tried png?

**Comment by goszowski** [comment]
png works good

**Comment by SimplyCorey** [comment]
This is resolved in v3 which I am finishing up the docs for and will push up this week.
